---
title: "Curso de R"
author: "Derek Corcoran"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# BIO 4022. Análisis y manipulación de datos en R

### En el inicio se encuentra:

- Read me file, explicación del contenido de este repositorio
- El pdf con el temario y evaluación del curso

### En la carpeta  de cada clase se encuentra:

- el archivo Rpres y HTML correspondiente a cada clase 
- Los datos, figuras o links utilizados para cada clase

# Links a las Clases en html

- Antes de empezar, si no has utilizado R anteriormente por favor revisa este 
  [Video](https://youtu.be/w6L7Ye18yPE) y realiza las primeras 7 lecciones de 
  *R Programming* en Swirl
- [Clase 1](https://derek-corcoran-barrios.github.io/Clase1/Clase1TidyData)
- [Clase 2](http://rpubs.com/derek_corcoran/Clase2). También puedes ver el video de la clase.

<iframe width="560" height="315" src="https://www.youtube.com/embed/Ft6r7pD_eSs" frameborder="0" allowfullscreen></iframe>

- [Clase 3](http://rpubs.com/derek_corcoran/Clase3). También puedes ver el video de la clase.
    + Video que muestra como [realizar](https://youtu.be/lDp5OJzeG34) el ejercicio 3 de la clase.
    
<iframe width="560" height="315" src="https://www.youtube.com/embed/5tjCeFb2oSk" frameborder="0" allowfullscreen></iframe>

- [Clase 4](http://rpubs.com/derek_corcoran/Clase4). También puedes ver el [video](https://youtu.be/miqDWpVEMRg) de la clase.


- [Clase 5](http://rpubs.com/derek_corcoran/Clase5). También puedes ver el [video](https://youtu.be/bvzi88XRq4c) de la clase.
- [Clase 6](http://rpubs.com/derek_corcoran/Clase6). También puedes ver el [video](https://youtu.be/nGb2__ksaho) de la clase.
- [Clase 7](http://rpubs.com/derek_corcoran/Clase7). También puedes ver el [video](https://youtu.be/_deboekuWt0) de la clase.

# Evaluaciones

* Pueden ver en este [link](http://rpubs.com/derek_corcoran/NotasBIO4022_2_2017) la evaluación de la primera tarea.
* En este [link](http://rpubs.com/derek_corcoran/Eval2) pueden ver la evaluación de la segunda tarea
* Finalmente en este [link](http://rpubs.com/derek_corcoran/NotasBIO4022_2_final2017) se encuentran las notas finales.
