---
title: "NBA Projections 2018 season"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


These are the projected standings predicted by our spatial-based algorithm as of `r format(Sys.time(), '%d %B, %Y')`

```{r Shotscrub, echo=FALSE, message=FALSE, warning=FALSE}
#Data 2018

if (!require("pacman")) install.packages("pacman")

pacman::p_load(rjson, grid, gridExtra, png, RCurl, ggplot2, jpeg, hexbin, sp, knitr, dplyr, lubridate)

by_team <- readRDS("by_team.rds")

teamID <- by_team$team_id
teamName <- by_team$team_city
Season2018 <- list()


shotURLtotal <- paste("http://stats.nba.com/stats/shotchartdetail?CFID=33&CFPARAMS=2017-18&ContextFilter=&ContextMeasure=FGA&DateFrom=&DateTo=&GameID=&GameSegment=&LastNGames=0&LeagueID=00&Location=&MeasureType=Base&Month=0&OpponentTeamID=0&Outcome=&PaceAdjust=N&PerMode=PerGame&Period=0&PlayerID=0&PlusMinus=N&Position=&Rank=N&RookieYear=&Season=2017-18&SeasonSegment=&SeasonType=Regular+Season&TeamID=0&VsConference=&VsDivision=&mode=Advanced&showDetails=0&showShots=1&showZones=0&PlayerPosition=", sep = "")

# import from JSON
Season2018 <- fromJSON(file = shotURLtotal, method="C")
Names <- Season2018$resultSets[[1]][[2]]
# unlist shot data, save into a data frame
Season2018 <- data.frame(matrix(unlist(Season2018$resultSets[[1]][[3]]), ncol = 24, byrow = TRUE))

colnames(Season2018) <- Names


# covert x and y coordinates into numeric
Season2018$LOC_X <- as.numeric(as.character(Season2018$LOC_X))
Season2018$LOC_Y <- as.numeric(as.character(Season2018$LOC_Y))


Season2018$TEAM_NAME <- gsub("Detroit Pistons", "Det", Season2018$TEAM_NAME)
Season2018$TEAM_NAME <- gsub("Atlanta Hawks", "Atl", Season2018$TEAM_NAME)
Season2018$TEAM_NAME <- gsub("Chicago Bulls", "Chi", Season2018$TEAM_NAME)
Season2018$TEAM_NAME <- gsub("Boston Celtics", "Bos", Season2018$TEAM_NAME)
Season2018$TEAM_NAME <- gsub("Cleveland Cavaliers", "Cle", Season2018$TEAM_NAME)
Season2018$TEAM_NAME <- gsub("New Orleans Pelicans", "NO", Season2018$TEAM_NAME)
Season2018$TEAM_NAME <- gsub("Golden State Warriors", "GSW", Season2018$TEAM_NAME)
Season2018$TEAM_NAME <- gsub("Orlando Magic", "ORL", Season2018$TEAM_NAME)
Season2018$TEAM_NAME <- gsub("Washington Wizards", "Was", Season2018$TEAM_NAME)
Season2018$TEAM_NAME <- gsub("Philadelphia 76ers", "Phi", Season2018$TEAM_NAME)
Season2018$TEAM_NAME <- gsub("Brooklyn Nets", "Bkn", Season2018$TEAM_NAME)
Season2018$TEAM_NAME <- gsub("Utah Jazz", "Uta", Season2018$TEAM_NAME)
Season2018$TEAM_NAME <- gsub("Miami Heat", "Mia", Season2018$TEAM_NAME)
Season2018$TEAM_NAME <- gsub("Charlotte Hornets", "Cha", Season2018$TEAM_NAME)
Season2018$TEAM_NAME <- gsub("Toronto Raptors", "Tor", Season2018$TEAM_NAME)
Season2018$TEAM_NAME <- gsub("Indiana Pacers", "Ind", Season2018$TEAM_NAME)
Season2018$TEAM_NAME <- gsub("Houston Rockets", "Hou", Season2018$TEAM_NAME)
Season2018$TEAM_NAME <- gsub("Denver Nuggets", "Den", Season2018$TEAM_NAME)
Season2018$TEAM_NAME <- gsub("Memphis Grizzlies", "Mem", Season2018$TEAM_NAME)
Season2018$TEAM_NAME <- gsub("New York Knicks", "NY", Season2018$TEAM_NAME)
Season2018$TEAM_NAME <- gsub("Milwaukee Bucks", "Mil", Season2018$TEAM_NAME)
Season2018$TEAM_NAME <- gsub("Oklahoma City Thunder", "Okc", Season2018$TEAM_NAME)
Season2018$TEAM_NAME <- gsub("San Antonio Spurs", "Sas", Season2018$TEAM_NAME)
Season2018$TEAM_NAME <- gsub("Dallas Mavericks", "Dal", Season2018$TEAM_NAME)
Season2018$TEAM_NAME <- gsub("Phoenix Suns", "Pho", Season2018$TEAM_NAME)
Season2018$TEAM_NAME <- gsub("Portland Trail Blazers", "Por", Season2018$TEAM_NAME)
Season2018$TEAM_NAME <- gsub("LA Clippers", "Lac", Season2018$TEAM_NAME)
Season2018$TEAM_NAME <- gsub("Sacramento Kings", "Sac", Season2018$TEAM_NAME)
Season2018$TEAM_NAME <- gsub("Los Angeles Lakers", "Lal", Season2018$TEAM_NAME)
Season2018$TEAM_NAME <- gsub("Minnesota Timberwolves", "Min", Season2018$TEAM_NAME)


####HOME VISITOR


Season2018$HTM <- gsub("DET", "Det", Season2018$HTM)
Season2018$HTM <- gsub("ATL", "Atl", Season2018$HTM)
Season2018$HTM <- gsub("CHI", "Chi", Season2018$HTM)
Season2018$HTM <- gsub("BOS", "Bos", Season2018$HTM)
Season2018$HTM <- gsub("CLE", "Cle", Season2018$HTM)
Season2018$HTM <- gsub("NOP", "NO", Season2018$HTM)
Season2018$HTM <- gsub("GSW", "GSW", Season2018$HTM)
Season2018$HTM <- gsub("ORL", "ORL", Season2018$HTM)
Season2018$HTM <- gsub("WAS", "Was", Season2018$HTM)
Season2018$HTM <- gsub("PHI", "Phi", Season2018$HTM)
Season2018$HTM <- gsub("BKN", "Bkn", Season2018$HTM)
Season2018$HTM <- gsub("UTA", "Uta", Season2018$HTM)
Season2018$HTM <- gsub("MIA", "Mia", Season2018$HTM)
Season2018$HTM <- gsub("CHA", "Cha", Season2018$HTM)
Season2018$HTM <- gsub("TOR", "Tor", Season2018$HTM)
Season2018$HTM <- gsub("IND", "Ind", Season2018$HTM)
Season2018$HTM <- gsub("HOU", "Hou", Season2018$HTM)
Season2018$HTM <- gsub("DEN", "Den", Season2018$HTM)
Season2018$HTM <- gsub("MEM", "Mem", Season2018$HTM)
Season2018$HTM <- gsub("NYK", "NY", Season2018$HTM)
Season2018$HTM <- gsub("MIL", "Mil", Season2018$HTM)
Season2018$HTM <- gsub("OKC", "Okc", Season2018$HTM)
Season2018$HTM <- gsub("SAS", "Sas", Season2018$HTM)
Season2018$HTM <- gsub("DAL", "Dal", Season2018$HTM)
Season2018$HTM <- gsub("PHX", "Pho", Season2018$HTM)
Season2018$HTM <- gsub("POR", "Por", Season2018$HTM)
Season2018$HTM <- gsub("LAC", "Lac", Season2018$HTM)
Season2018$HTM <- gsub("SAC", "Sac", Season2018$HTM)
Season2018$HTM <- gsub("LAL", "Lal", Season2018$HTM)
Season2018$HTM <- gsub("MIN", "Min", Season2018$HTM)

###Visitor


Season2018$VTM <- gsub("DET", "Det", Season2018$VTM)
Season2018$VTM <- gsub("ATL", "Atl", Season2018$VTM)
Season2018$VTM <- gsub("CHI", "Chi", Season2018$VTM)
Season2018$VTM <- gsub("BOS", "Bos", Season2018$VTM)
Season2018$VTM <- gsub("CLE", "Cle", Season2018$VTM)
Season2018$VTM <- gsub("NOP", "NO", Season2018$VTM)
Season2018$VTM <- gsub("GSW", "GSW", Season2018$VTM)
Season2018$VTM <- gsub("ORL", "ORL", Season2018$VTM)
Season2018$VTM <- gsub("WAS", "Was", Season2018$VTM)
Season2018$VTM <- gsub("PHI", "Phi", Season2018$VTM)
Season2018$VTM <- gsub("BKN", "Bkn", Season2018$VTM)
Season2018$VTM <- gsub("UTA", "Uta", Season2018$VTM)
Season2018$VTM <- gsub("MIA", "Mia", Season2018$VTM)
Season2018$VTM <- gsub("CHA", "Cha", Season2018$VTM)
Season2018$VTM <- gsub("TOR", "Tor", Season2018$VTM)
Season2018$VTM <- gsub("IND", "Ind", Season2018$VTM)
Season2018$VTM <- gsub("HOU", "Hou", Season2018$VTM)
Season2018$VTM <- gsub("DEN", "Den", Season2018$VTM)
Season2018$VTM <- gsub("MEM", "Mem", Season2018$VTM)
Season2018$VTM <- gsub("NYK", "NY", Season2018$VTM)
Season2018$VTM <- gsub("MIL", "Mil", Season2018$VTM)
Season2018$VTM <- gsub("OKC", "Okc", Season2018$VTM)
Season2018$VTM <- gsub("SAS", "Sas", Season2018$VTM)
Season2018$VTM <- gsub("DAL", "Dal", Season2018$VTM)
Season2018$VTM <- gsub("PHX", "Pho", Season2018$VTM)
Season2018$VTM <- gsub("POR", "Por", Season2018$VTM)
Season2018$VTM <- gsub("LAC", "Lac", Season2018$VTM)
Season2018$VTM <- gsub("SAC", "Sac", Season2018$VTM)
Season2018$VTM <- gsub("LAL", "Lal", Season2018$VTM)
Season2018$VTM <- gsub("MIN", "Min", Season2018$VTM)
Season2018$GAME_DATE <- ymd(Season2018$GAME_DATE)
```


```{r schedulescrub, echo=FALSE, message=FALSE, warning=FALSE}

pacman::p_load(XML, lubridate, rvest, dplyr)
#Gather data

Months <- c("october", "november", "december", "january", "february", "march", "april")
Years <- c(2018)
URLs <- list()
for(i in 1:length(Years)){
  URLs[[i]] <- paste("http://www.basketball-reference.com/leagues/NBA_", Years[i],"_games-", Months,".html", sep = "")
}

URLs <- do.call("c", URLs)
URLs <- data.frame(URLs = URLs, Year = as.numeric(gsub("\\D", "", URLs)))
URLs$URLs <- as.character(URLs$URLs)
schedule <- list()
# import from JSON

for(i in 1:nrow(URLs)){
  schedule[[i]] <- read_html(URLs$URLs[i])%>% html_table(fill=TRUE)%>% .[[1]]
}

schedule <- do.call("rbind", schedule)

schedule$Date <- mdy(as.character(schedule$Date))
schedule[,4] <- as.numeric(as.character(schedule[,4]))
schedule[,6] <- as.numeric(as.character(schedule[,6]))


schedule$Season <- 2018


schedule[,3] <- gsub("Detroit Pistons", "Det", schedule[,3])
schedule[,3] <- gsub("Atlanta Hawks", "Atl", schedule[,3])
schedule[,3] <- gsub("Chicago Bulls", "Chi", schedule[,3])
schedule[,3] <- gsub("Boston Celtics", "Bos", schedule[,3])
schedule[,3] <- gsub("Cleveland Cavaliers", "Cle", schedule[,3])
schedule[,3] <- gsub("New Orleans Pelicans", "NO", schedule[,3])
schedule[,3] <- gsub("Golden State Warriors", "GSW", schedule[,3])
schedule[,3] <- gsub("Orlando Magic", "ORL", schedule[,3])
schedule[,3] <- gsub("Washington Wizards", "Was", schedule[,3])
schedule[,3] <- gsub("Philadelphia 76ers", "Phi", schedule[,3])
schedule[,3] <- gsub("Brooklyn Nets", "Bkn", schedule[,3])
schedule[,3] <- gsub("Utah Jazz", "Uta", schedule[,3])
schedule[,3] <- gsub("Miami Heat", "Mia", schedule[,3])
schedule[,3] <- gsub("Charlotte Hornets", "Cha", schedule[,3])
schedule[,3] <- gsub("Toronto Raptors", "Tor", schedule[,3])
schedule[,3] <- gsub("Indiana Pacers", "Ind", schedule[,3])
schedule[,3] <- gsub("Houston Rockets", "Hou", schedule[,3])
schedule[,3] <- gsub("Denver Nuggets", "Den", schedule[,3])
schedule[,3] <- gsub("Memphis Grizzlies", "Mem", schedule[,3])
schedule[,3] <- gsub("New York Knicks", "NY", schedule[,3])
schedule[,3] <- gsub("Milwaukee Bucks", "Mil", schedule[,3])
schedule[,3] <- gsub("Oklahoma City Thunder", "Okc", schedule[,3])
schedule[,3] <- gsub("San Antonio Spurs", "Sas", schedule[,3])
schedule[,3] <- gsub("Dallas Mavericks", "Dal", schedule[,3])
schedule[,3] <- gsub("Phoenix Suns", "Pho", schedule[,3])
schedule[,3] <- gsub("Portland Trail Blazers", "Por", schedule[,3])
schedule[,3] <- gsub("Los Angeles Clippers", "Lac", schedule[,3])
schedule[,3] <- gsub("Sacramento Kings", "Sac", schedule[,3])
schedule[,3] <- gsub("Los Angeles Lakers", "Lal", schedule[,3])
schedule[,3] <- gsub("Minnesota Timberwolves", "Min", schedule[,3])
schedule[,3] <- gsub("Charlotte Bobcats", "Cha", schedule[,3])
schedule[,3]<- gsub("New Orleans Hornets", "NO", schedule[,3])



schedule[,5] <- gsub("Detroit Pistons", "Det", schedule[,5])
schedule[,5] <- gsub("Atlanta Hawks", "Atl", schedule[,5])
schedule[,5] <- gsub("Chicago Bulls", "Chi", schedule[,5])
schedule[,5] <- gsub("Boston Celtics", "Bos", schedule[,5])
schedule[,5] <- gsub("Cleveland Cavaliers", "Cle", schedule[,5])
schedule[,5] <- gsub("New Orleans Pelicans", "NO", schedule[,5])
schedule[,5] <- gsub("Golden State Warriors", "GSW", schedule[,5])
schedule[,5] <- gsub("Orlando Magic", "ORL", schedule[,5])
schedule[,5] <- gsub("Washington Wizards", "Was", schedule[,5])
schedule[,5] <- gsub("Philadelphia 76ers", "Phi", schedule[,5])
schedule[,5] <- gsub("Brooklyn Nets", "Bkn", schedule[,5])
schedule[,5] <- gsub("Utah Jazz", "Uta", schedule[,5])
schedule[,5] <- gsub("Miami Heat", "Mia", schedule[,5])
schedule[,5] <- gsub("Charlotte Hornets", "Cha", schedule[,5])
schedule[,5] <- gsub("Toronto Raptors", "Tor", schedule[,5])
schedule[,5] <- gsub("Indiana Pacers", "Ind", schedule[,5])
schedule[,5] <- gsub("Houston Rockets", "Hou", schedule[,5])
schedule[,5] <- gsub("Denver Nuggets", "Den", schedule[,5])
schedule[,5] <- gsub("Memphis Grizzlies", "Mem", schedule[,5])
schedule[,5] <- gsub("New York Knicks", "NY", schedule[,5])
schedule[,5] <- gsub("Milwaukee Bucks", "Mil", schedule[,5])
schedule[,5] <- gsub("Oklahoma City Thunder", "Okc", schedule[,5])
schedule[,5] <- gsub("San Antonio Spurs", "Sas", schedule[,5])
schedule[,5] <- gsub("Dallas Mavericks", "Dal", schedule[,5])
schedule[,5] <- gsub("Phoenix Suns", "Pho", schedule[,5])
schedule[,5] <- gsub("Portland Trail Blazers", "Por", schedule[,5])
schedule[,5] <- gsub("Los Angeles Clippers", "Lac", schedule[,5])
schedule[,5] <- gsub("Sacramento Kings", "Sac", schedule[,5])
schedule[,5] <- gsub("Los Angeles Lakers", "Lal", schedule[,5])
schedule[,5] <- gsub("Minnesota Timberwolves", "Min", schedule[,5])
schedule[,5] <- gsub("Charlotte Bobcats", "Cha", schedule[,5])
schedule[,5]<- gsub("New Orleans Hornets", "NO", schedule[,5])

```

```{r simulatingGames, echo=FALSE, message=FALSE, warning=FALSE}
pacman::p_load(SpatialBall, dplyr)

colnames(schedule) <- c("Date", "Start..ET.","VTM", "PTS_Visitor", "HTM", "PTS_Home", "X", "X2", "Notes", "Season")

schedule <- dplyr::select(schedule, Date, VTM, PTS_Visitor, HTM, PTS_Home, Season)

future_games <- schedule[schedule$Date >= Sys.Date(),]


results <- list()
for(i in 1:nrow(future_games)){
  results[[i]] <- Get_Apps(HomeTeam = future_games$HTM[i], VisitorTeam = future_games$VTM[i], Seasondata = Season2018)
  message(paste("simulating", i ,"of", nrow(future_games)))
}

results <- do.call(rbind, results)

future_games <- cbind(future_games, results)

future_games$Home <- ifelse(future_games$spread < 0, "W", "L")

future_games$Visit <- ifelse(future_games$spread > 0, "W", "L")


Home <- cbind(future_games$HTM, future_games$Home)

colnames(Home) <- c("Team", "Result")

Visit <- cbind(future_games$VTM, future_games$Visit)

colnames(Visit) <- c("Team", "Result")

AddedStand <- data.frame(rbind(Home, Visit))
#Wins
AddedStand_W <- dplyr::filter(AddedStand, Result == "W")

AddedStand_W <- group_by(AddedStand_W, Team)

AddedStand_W <- dplyr::summarize(AddedStand_W, W = n())

#Loses

AddedStand_L <- dplyr::filter(AddedStand, Result == "L")

AddedStand_L <- group_by(AddedStand_L, Team)

AddedStand_L <- dplyr::summarize(AddedStand_L, L = n())

AddedStand <- merge.data.frame(AddedStand_W, AddedStand_L, all = TRUE)


#####Standing scraper

Standings <- "http://www.basketball-reference.com/leagues/NBA_2018.html"

Standings <- read_html(Standings)%>% html_table(fill=TRUE)%>% .[1:2]

Standings <- list(Western = Standings[[2]], Eastern = Standings[[1]])
Standings[[1]]$Conference <- c("West")

Standings[[2]]$Conference <- c("East")

colnames(Standings[[1]]) <- c("Team", "Current-W", "Current-L", "pct", "GB", "PS/G", "PA/G", "SRS", "Conference")

colnames(Standings[[2]]) <- c("Team", "Current-W", "Current-L", "pct", "GB", "PS/G", "PA/G", "SRS", "Conference")


Standings <- rbind(Standings[[1]], Standings[[2]])

Standings <- Standings[,c(1,2,3,9)]

Standings$Team <- gsub("76ers", "Phi", Standings$Team)


Standings$Team <- gsub("(?<=\\b[A-Z])[^A-Z]+", "", Standings$Team, perl = TRUE)

Standings$Team <- gsub("DP", "Det", Standings$Team)
Standings$Team<- gsub("AH", "Atl", Standings$Team)
Standings$Team <- gsub("CB", "Chi", Standings$Team)
Standings$Team<- gsub("BC", "Bos", Standings$Team)
Standings$Team<- gsub("CC", "Cle", Standings$Team)
Standings$Team<- gsub("NOP", "NO", Standings$Team)
Standings$Team<- gsub("OM", "ORL", Standings$Team)
Standings$Team<- gsub("WW", "Was", Standings$Team)
Standings$Team<- gsub("BN", "Bkn", Standings$Team)
Standings$Team<- gsub("UJ", "Uta", Standings$Team)
Standings$Team<- gsub("MH", "Mia", Standings$Team)
Standings$Team<- gsub("CH", "Cha", Standings$Team)
Standings$Team<- gsub("TR", "Tor", Standings$Team)
Standings$Team<- gsub("IP", "Ind", Standings$Team)
Standings$Team<- gsub("HR", "Hou", Standings$Team)
Standings$Team<- gsub("DN", "Den", Standings$Team)
Standings$Team<- gsub("MG", "Mem", Standings$Team)
Standings$Team<- gsub("NYK", "NY", Standings$Team)
Standings$Team<- gsub("MB", "Mil", Standings$Team)
Standings$Team<- gsub("OCT", "Okc", Standings$Team)
Standings$Team<- gsub("SAS", "Sas", Standings$Team)
Standings$Team<- gsub("DM", "Dal", Standings$Team)
Standings$Team<- gsub("PS", "Pho", Standings$Team)
Standings$Team<- gsub("PTB", "Por", Standings$Team)
Standings$Team<- gsub("LAC", "Lac", Standings$Team)
Standings$Team<- gsub("SK", "Sac", Standings$Team)
Standings$Team<- gsub("LAL", "Lal", Standings$Team)
Standings$Team<- gsub("MT", "Min", Standings$Team)
Standings$Team<- gsub("PP", "Phi", Standings$Team)

ProjStand <- merge.data.frame(Standings, AddedStand, all = TRUE)

ProjStand[,2] <- as.numeric(as.character(ProjStand[,2]))
ProjStand[,3] <- as.numeric(as.character(ProjStand[,3]))


ProjStand$W <- ProjStand$`Current-W`+ProjStand$W
ProjStand$L <- ProjStand$`Current-L`+ProjStand$L


colnames(ProjStand) <- c("Team", "Current-W", "Current-L", "Conference", "Projected-W", "Projected-L")

ProjStand$`Projected-L`<- ifelse(is.na(ProjStand$`Projected-L`), ProjStand$`Current-L`, ProjStand$`Projected-L`)

ProjStand$`Projected-W`<- ifelse(is.na(ProjStand$`Projected-W`), ProjStand$`Current-W`, ProjStand$`Projected-W`)

ProjStand <- arrange(ProjStand, Conference,desc(`Projected-W`))



ProjStandW <- dplyr::filter(ProjStand, Conference == "West")

ProjStandE <- dplyr::filter(ProjStand, Conference == "East")
```

## Eastern Conference Standings

```{r, echo=FALSE, message=FALSE, warning=FALSE}
#options(DT.options = list(pageLength = 20, language = list(search = 'Filter:')))
#knitr::kable(ProjStandE)
ProjStandE <- ProjStandE %>% mutate_if(is.numeric, funs(round(., 3)))
DT::datatable(ProjStandE,  options = list(
  autoWidth = TRUE, pageLength = 15
))
```


## Western Conference Standings

```{r, echo=FALSE, message=FALSE, warning=FALSE}
#knitr::kable(ProjStandW)
ProjStandW <- ProjStandW %>% mutate_if(is.numeric, funs(round(., 3)))
DT::datatable(ProjStandW,  options = list(
  autoWidth = TRUE, pageLength = 15
))


```

## Game predictions

In the table below we present the predicted spread for every NBA game played on `r format(Sys.time(), '%d %B, %Y')`

```{r, echo=FALSE, message=FALSE, warning=FALSE}
#knitr::kable(dplyr::filter(future_games[,c(1,2,4,9,10,11)], Date == Sys.Date()), digits = 3)
DT::datatable(dplyr::filter(future_games[,c(1,2,4,9,10,11)], Date == Sys.Date()),  options = list(
  autoWidth = TRUE, pageLength = 30
))
#write.csv(x = dplyr::filter(future_games, Date == Sys.Date()), file =   paste("Future_games", Sys.Date(),".csv", sep = ""))
#saveRDS(dplyr::filter(future_games, Date == Sys.Date()),  paste("Future_games", Sys.Date(),".rds", sep = ""))
```