# El Tidyverso {#tidyverso}

## Paquetes necesarios para este capítulo

Para este capitulo necesitas tener instalado el paquete *tidyverse*

En este capítulo se explicará qué es el paquete *tidyverse* [@Wickhamtidyverse] y cuales son sus componentes, ya demás veremos las funciones del paqute *tidyr* [@Wickhamtidy], con sus dos funciones `gather` y `spread`.

Dado que este libro es un apoyo para el curso BIO4022, esta clase del curso puede también ser seguida en este [link](https://derek-corcoran-barrios.github.io/Clase3/Clase3Hadleyverso). El video de la clase se encontrará disponible en este link.

## El tidiverso

El tidiverso se refiere al paquete [tidiverse](https://www.tidyverse.org/), el cual es una colección de paquetes coehrentes, que tienen una gramática, filosofía y estructura similar. Todos se basan el la idea de tidy data propuesta por Hadley Wickham [@wickham2014tidy]. Los paquetes que forman parte del tidyverso son:

* readr (ya la estamos usando)
* dplyr (Clase anterior)
* tidyr (Hoy)
* forcats (Para variables categóricas)
* stringr (Para carácteres, Palabras)
* ggplot2 (Próxima clase)
* purrr (En clase sobre loops)

### readr

El paquete *readr* [@Wickhamreadr] tiene como función el leer y exportar archivos. En general nosotros usaremos archivos del tipo *csv*. Para este tipo de archivos, *readr* tiene la función `read_csv`. Para exportar un archivo ocupamos la función `write_csv`. Ambas funciones son 10 veces más rápidas que las versiones de r base. Para más información sobre este revisar su [página oficial](https://readr.tidyverse.org/).

### dplyr

Este paquete sirve para modificar variables, los detalles de este paquete los vemos en el capítulo \@ref(tidydata). Los cinco verbos principales que tiene son `mutate` para generar nuevas variables, que vienen de variables ya existentes, `select` para seleccionar variables basadas en su nombre, `filter` para seleccionar filas de acuerdo a si cumplen o no con condiciones en una o mas variables, `summarize` para resumir las variables, y `arrange` para reordenar las filas de acuerdo a alguna variable. Para más información sobre este paquete revisar su [pagina oficial](https://dplyr.tidyverse.org/).

### tidyr

