---
title: "Map Husby"
author: "Derek Corcoran"
date: "8/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, cache = FALSE)
library(tidyverse)
library(leaflet)
library(sf)
library(raster)
library(janitor)

Husby_Raster <- read_rds("HusbyRaster.rds")

Husby_Roads <- read_rds("roads_Husby.rds") %>% st_transform(crs ="+proj=longlat +datum=WGS84 +no_defs")


Husby_Raster <- Husby_Raster[[1]] %>% projectRaster(crs ="+proj=longlat +datum=WGS84 +no_defs")

Husby <- read_sf("GroupsHusby.shp") %>% 
  st_transform(crs = "+proj=longlat +datum=WGS84 +no_defs") %>% 
  mutate(Group = case_when(Group == 1 ~ "A1",
                           Group == 2 ~ "A2",
                           Group == 3 ~ "B1",
                           Group == 4 ~ "B2",
                           Group == 5 ~ "C1",
                           Group == 6 ~ "C2"))

Husby_Large <- read_sf("GroupsHusbyLarge.shp") %>% 
  st_transform(crs = "+proj=longlat +datum=WGS84 +no_defs") %>% 
  mutate(Group = case_when(Group == 1 ~ "A1",
                           Group == 2 ~ "A2",
                           Group == 3 ~ "B1",
                           Group == 4 ~ "B2",
                           Group == 5 ~ "C1",
                           Group == 6 ~ "C2"))

Husby_Centroids <- read_sf("Husby_centroids.shp") %>% 
  st_transform(crs = "+proj=longlat +datum=WGS84 +no_defs")%>% 
  mutate(Group = case_when(Group == 1 ~ "A1",
                           Group == 2 ~ "A2",
                           Group == 3 ~ "B1",
                           Group == 4 ~ "B2",
                           Group == 5 ~ "C1",
                           Group == 6 ~ "C2"))

Husby_Centroids <- Husby_Centroids %>% 
  mutate(Code = paste(Group, formatC(rowid, digits = 2, flag = "0"), sep = "_"), Treatment = NA) %>% group_by(Code) %>% group_split()

Treatments <- LETTERS[1:3]

for(i in 1:length(Husby_Centroids)){
  set.seed(i)
  Husby_Centroids[[i]]$Treatment <- sample(Treatments, replace = F)
}

Husby_Centroids <- Husby_Centroids %>% reduce(bind_rows) %>% 
  mutate(Code = paste(Code, Treatment, sep = "_")) %>% 
  dplyr::select(-Treatment)

write_sf(Husby_Centroids, "Final_Centroids_Husby.shp")


Husby_Monitor <- list()

for(i in 1:nrow(Husby)){
  set.seed(i)
  Mask <- mask(Husby_Raster, Husby[i,])
  Pres <- Husby_Centroids %>% dplyr::filter(Group == Husby[i,]$Group[1]) %>% as_Spatial()
  RandomPoints <- dismo::randomPoints(Mask, n = 30, p = Pres) %>% 
    as.data.frame() %>% 
    st_as_sf(coords = c(1,2), crs ="+proj=longlat +datum=WGS84 +no_defs") %>% 
    mutate(Group = Husby[i,]$Group[1]) %>% 
    st_transform(crs = "+proj=utm +zone=32 +ellps=GRS80 +units=m +no_defs") %>% 
    st_buffer(dist = 25) %>% 
    st_transform(crs ="+proj=longlat +datum=WGS84 +no_defs") 
  for(j in i:nrow(RandomPoints)){
    if(j == 1){
      Temp <- RandomPoints[j,]
    }
    else if (j != 1 & sum(st_intersects(Temp, RandomPoints[j,], sparse = F)) == 0){
      Temp <- rbind(Temp, RandomPoints[j,])
      print(j)
    }
  }
  Husby_Monitor[[i]] <- Temp %>% st_centroid() %>% dplyr::distinct()
}

Husby_Monitor <- Husby_Monitor %>% reduce(rbind) %>% dplyr::distinct()

Husby_Monitor <- Husby_Monitor %>% group_split(Group) %>% purrr::map(~tibble::rowid_to_column(.x)) %>% reduce(rbind)

separated_coord <- Husby_Monitor %>% 
  mutate(lat = unlist(map(Husby_Monitor$geometry,1)),
         long = unlist(map(Husby_Monitor$geometry,2))) %>% 
  as.data.frame() %>% 
  dplyr::select(lat, long) %>% 
  dplyr::distinct()

Husby_Monitor <- Husby_Monitor %>% 
  cbind(separated_coord) %>% 
  mutate(Code = paste("M", Group, rowid, sep = "_")) %>% 
  dplyr::select(-rowid)
write_sf(Husby_Monitor, "Husby_Monitor.shp")
```

```{r}

Klit2 <- read_csv("Husby_klit.csv") %>% 
  janitor::clean_names() %>% 
  dplyr::select("plot_id", "natur_vurderet_som2") %>% 
  rename(id = plot_id, natur = natur_vurderet_som2)

Klit <- read_sf("husby_klit_sample.shp") %>% 
  dplyr::select(lat, long, id) %>% 
  merge(Klit2) %>% 
  mutate(natur = as.character(natur)) %>% 
  st_transform() %>% 
  st_transform(crs ="+proj=longlat +datum=WGS84 +no_defs") %>% 
  st_intersection(Husby_Large) %>% 
  mutate(Code = paste("J", Group, natur, formatC(id, digits = 2, flag = "0"), sep = "_"))

Husby_outline <- Husby %>% st_union() %>% st_as_sf() %>% st_cast("POLYGON")

Husby_Centroids <- Husby_Centroids %>% 
  rbind(read_rds("Final_ones_out.husby.rds")) %>% 
  arrange(Code) %>% 
  mutate(Code = paste("E", Code, sep = "_"))

l <-leaflet()

esri <- grep("^Esri", providers, value = TRUE)
esri <- esri[c(5,2,4,10)]

pal <- colorFactor(
  palette = c("#9e0142", "#d53e4f", "#fee08b", "#ffffbf", "#66c2a5", "#3288bd"),
  domain= as.character(sort(unique(Husby_Centroids$Group))),
  ordered = TRUE,
  na.color = "#808080"
)

for (provider in esri) {
  l <- l %>% addProviderTiles(provider, group = provider)    
}

l <- l %>% 
     leaflet::addCircleMarkers(data = as_Spatial(Klit), radius = 6, group = "Julie", color = "grey", popup = paste("Lon:", Klit$long, "<br>",
                           "Lat:", Klit$lat, "<br>",
                           "Group:", Klit$Group, "<br>",
                           "Natur", Klit$natur,"<br>",
                           "Code:", Klit$Code)) %>%
    leaflet::addCircleMarkers(data = as_Spatial(Husby_Monitor), radius = 6, group = "Monitoring", color = ~pal(Group), popup = paste("Lon:", Husby_Monitor$long, "<br>",
                           "Lat:", Husby_Monitor$lat, "<br>",
                           "Code:",Husby_Monitor$Code)) %>% 
    leaflet::addCircleMarkers(data = as_Spatial(Husby_Centroids), radius = 6, group = "Points", color = ~pal(Group), popup = paste("Lon:", Husby_Centroids$long, "<br>",
                           "Lat:", Husby_Centroids$lat, "<br>",
                           "Group:", Husby_Centroids$Group, "<br>", 
                           "Code:", Husby_Centroids$Code)) %>%
  addPolygons(data = as_Spatial(Husby), group = "Groups", color = ~pal(Group), fillColor = ~pal(Group), opacity = 0.8, popup = Husby$Group, fillOpacity = 0.8) %>% 
  addPolygons(data = as_Spatial(Husby_Large), group = "Large groups", color = ~pal(Group), fillColor = ~pal(Group), opacity = 0.8, popup = Husby_Large$Group, fillOpacity = 0.8) %>% 
 addPolylines(data = Husby_Roads, color = "red", group = "Roads") %>% 
  addPolylines(data = as_Spatial(Husby_outline), color = "blue", fillOpacity = 0, group = "Outline") %>% 
  addLayersControl(baseGroups = names(esri),
                   overlayGroups = c("Points", "Groups", "Monitoring", "Julie", "Roads", "Large groups", "Outline"),
                   options = layersControlOptions(collapsed = TRUE)) %>%
  addMeasure(position = "topleft",
             primaryLengthUnit = "meters",
             primaryAreaUnit = "hectares") %>% 
  hideGroup(c("Groups", "Large groups"))

l %>% addLegend("bottomright", pal = pal ,title = "Husby sites",opacity = 1, values = Husby_Centroids$Group) %>%
  addEasyButton(easyButton(
    icon="fa-croshairs", title="Locate Me",
    onClick=JS("function(btn, map){ map.locate({setView: true}); }")))

#All_Points_Husby <- list(Husby_Centroids, Husby_Monitor, Klit) %>% purrr::map(~dplyr::select(.x, Code)) %>% purrr::map(~dplyr::relocate(.x, Code, .before = everything())) %>% purrr::reduce(rbind)

#ToGPX <- All_Points_Husby %>% arrange(Code) %>% dplyr::select(Code) %>% 
#  st_transform("+proj=longlat + ellps=WGS84") %>% 
#  as_Spatial()

# use the ID field for the names
#ToGPX@data$name <- ToGPX@data$Code  
#library(rgdal)
#Now only write the "name" field to the file
#writeOGR(ToGPX["name"], driver="GPX", layer="waypoints", 
         dsn="AllPointsHusby.gpx")

```
