---
title: "Map Husby Monitoring"
author: "Derek Corcoran"
date: "31/08/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, cache = FALSE)
library(tidyverse)
library(leaflet)
library(sf)
library(raster)
library(janitor)

Husby_Raster <- read_rds("HusbyRaster.rds")

Husby_Roads <- read_rds("roads_Husby.rds") %>% st_transform(crs ="+proj=longlat +datum=WGS84 +no_defs")


Husby_Raster <- Husby_Raster[[1]] %>% projectRaster(crs ="+proj=longlat +datum=WGS84 +no_defs")

Husby <- read_sf("GroupsHusby.shp") %>% 
  st_transform(crs = "+proj=longlat +datum=WGS84 +no_defs") %>% 
  mutate(Group = case_when(Group == 1 ~ "A1",
                           Group == 2 ~ "A2",
                           Group == 3 ~ "B1",
                           Group == 4 ~ "B2",
                           Group == 5 ~ "C1",
                           Group == 6 ~ "C2"))

Husby_Large <- read_sf("GroupsHusbyLarge.shp") %>% 
  st_transform(crs = "+proj=longlat +datum=WGS84 +no_defs") %>% 
  mutate(Group = case_when(Group == 1 ~ "A1",
                           Group == 2 ~ "A2",
                           Group == 3 ~ "B1",
                           Group == 4 ~ "B2",
                           Group == 5 ~ "C1",
                           Group == 6 ~ "C2"))


Husby_Monitor <- read_sf("Husby - de sidste monitoring plots.kml") %>% 
  dplyr::filter(stringr::str_detect(description, "Skip", negate = T)) %>% 
  st_transform("+proj=longlat + ellps=WGS84") 

separated_coord <- Husby_Monitor %>% 
  mutate(lat = unlist(map(Husby_Monitor$geometry,1)),
         long = unlist(map(Husby_Monitor$geometry,2))) %>% 
  as.data.frame() %>% 
  dplyr::select(lat, long)




Husby_Monitor <- Husby_Monitor %>% 
  cbind(separated_coord) %>% 
  dplyr::select(Name, long, lat) %>% separate(Name, into = c("Site", "Type", "Group"), remove = F)
```

```{r}


Husby_outline <- Husby %>% st_union() %>% st_as_sf() %>% st_cast("POLYGON")


l <-leaflet()

esri <- grep("^Esri", providers, value = TRUE)
esri <- esri[c(5,2,4,10)]

pal <- colorFactor(
  palette = c("#9e0142", "#d53e4f", "#fee08b", "#ffffbf", "#66c2a5", "#3288bd"),
  domain= as.character(sort(unique(Husby$Group))),
  ordered = TRUE,
  na.color = "#808080"
)

for (provider in esri) {
  l <- l %>% addProviderTiles(provider, group = provider)    
}

l <- l %>%
    leaflet::addCircleMarkers(data = as_Spatial(Husby_Monitor), radius = 6, group = "Monitoring", color = ~pal(Group), popup = paste("Lon:", Husby_Monitor$long, "<br>",
                           "Lat:", Husby_Monitor$lat, "<br>",
                           "Code:",Husby_Monitor$Name))  %>%
  addPolygons(data = as_Spatial(Husby), group = "Groups", color = ~pal(Group), fillColor = ~pal(Group), opacity = 0.8, popup = Husby$Group, fillOpacity = 0.8) %>% 
  addPolygons(data = as_Spatial(Husby_Large), group = "Large groups", color = ~pal(Group), fillColor = ~pal(Group), opacity = 0.8, popup = Husby_Large$Group, fillOpacity = 0.8) %>% 
 addPolylines(data = Husby_Roads, color = "red", group = "Roads") %>% 
  addPolylines(data = as_Spatial(Husby_outline), color = "blue", fillOpacity = 0, group = "Outline") %>% 
  addLayersControl(baseGroups = names(esri),
                   overlayGroups = c("Groups", "Monitoring", "Roads", "Large groups", "Outline"),
                   options = layersControlOptions(collapsed = TRUE)) %>%
  addMeasure(position = "topleft",
             primaryLengthUnit = "meters",
             primaryAreaUnit = "hectares") %>% 
  hideGroup(c("Groups", "Large groups"))

l %>% addLegend("bottomright", pal = pal ,title = "Husby sites",opacity = 1, values = Husby$Group) %>%
  addEasyButton(easyButton(
    icon="fa-croshairs", title="Locate Me",
    onClick=JS("function(btn, map){ map.locate({setView: true}); }")))
```
