---
title: "Field Work map"
author: "Derek Corcoran"
date: "`r format(Sys.time(), '%d/%m, %Y')`"
output:
  ioslides_presentation:
    widescreen: true
    incremental: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, cache = FALSE, tidy = TRUE, tidy.opts= list(blank = FALSE, width.cutoff = 60))
library(leaflet)
library(kableExtra)
library(sf)
library(raster)
library(tidyverse)

OnlyPoints <- readRDS("Onlypoints4.rds")

options("kableExtra.html.bsTable" = T)
```

## Map 1

```{r, cache=FALSE}
library(leaflet)

Coords <- OnlyPoints %>% dplyr::filter(Rank > 0) %>% as_Spatial()

Coords <- Coords@coords %>% as.data.frame()

Coords2 <- OnlyPoints %>% st_transform(crs = "+proj=longlat +datum=WGS84") %>% dplyr::filter(Rank > 0) %>% as_Spatial()

Coords2 <- Coords2@coords %>% as.data.frame() %>% rename(Lon = coords.x1, Lat = coords.x2)

Test <- OnlyPoints %>% dplyr::filter(Rank > 0)%>% st_transform(crs = "+proj=longlat +datum=WGS84") %>% 
  mutate(Ranking = case_when(Rank == 1 ~ "Richness Trend",
                             Rank > 1 & Rank <= 200 ~ "2 - 200",
                             Rank > 200 & Rank <= 400 ~ "201 - 400",
                             Rank > 400 & Rank <= 600 ~ "401 - 600",
                             Rank > 600 & Rank <= 800 ~ "601 - 800",
                             Rank > 800 ~ "> 800"),
         Ranking = fct_relevel(Ranking, "Richness Trend", "2 - 200", "201 - 400","401 - 600", "601 - 800")) %>% 
  cbind(Coords) %>% 
  cbind(Coords2)
l <-leaflet()

esri <- grep("^Esri", providers, value = TRUE)
esri <- esri[c(5,2,4,10)]

pal <- colorFactor(
  palette = c("White",'#d7191c','#fdae61','#abd9e9','#2c7bb6', "black"),
  domain= Test$Ranking,
  ordered = TRUE,
  na.color = "#808080"
)

for (provider in esri) {
  l <- l %>% addProviderTiles(provider, group = provider) %>% 
    leaflet::addCircles(data = as_Spatial(dplyr::filter(Test, Ranking == "401 - 600")), group = "401 - 600", color = ~pal(Ranking), popup = paste("<b>Ranking:", dplyr::filter(Test, Ranking == "401 - 600")$Rank,"</b>", "<br>", 
                                                                                    "Habitat:", dplyr::filter(Test, Ranking == "401 - 600")$habtype, "<br>",
                                                                                    "Dataset:", Test$Dataset, "<br>",
                           "Canopy height:", dplyr::filter(Test, Ranking == "401 - 600")$Canopy_Height, "<br>",
                           "Sand:", round(dplyr::filter(Test, Ranking == "401 - 600")$afsandno + dplyr::filter(Test, Ranking == "401 - 600")$agsandno), "<br>",
                           "Coord x:", dplyr::filter(Test, Ranking == "401 - 600")$coords.x1, "<br>",
                           "Coord y:", dplyr::filter(Test, Ranking == "401 - 600")$coords.x2, "<br>",
                           "Lon:", dplyr::filter(Test, Ranking == "401 - 600")$Lon, "<br>",
                           "Lat:", dplyr::filter(Test, Ranking == "401 - 600")$Lat)) %>%
    leaflet::addCircles(data = as_Spatial(dplyr::filter(Test, Ranking == "201 - 400")), group = "201 - 400", color = ~pal(Ranking), popup = paste("<b>Ranking:", dplyr::filter(Test, Ranking == "201 - 400")$Rank,"</b>", "<br>", 
                                                                                    "Habitat:", dplyr::filter(Test, Ranking == "201 - 400")$habtype, "<br>",
                                                                                    "Dataset:", dplyr::filter(Test, Ranking == "201 - 400")$Dataset, "<br>",
                           "Canopy height:", dplyr::filter(Test, Ranking == "201 - 400")$Canopy_Height, "<br>",
                           "Sand:", round(dplyr::filter(Test, Ranking == "201 - 400")$afsandno + dplyr::filter(Test, Ranking == "201 - 400")$agsandno), "<br>",
                           "Coord x:", dplyr::filter(Test, Ranking == "201 - 400")$coords.x1, "<br>",
                           "Coord y:", dplyr::filter(Test, Ranking == "201 - 400")$coords.x2, "<br>",
                           "Lon:", dplyr::filter(Test, Ranking == "201 - 400")$Lon, "<br>",
                           "Lat:", dplyr::filter(Test, Ranking == "201 - 400")$Lat)) %>% 
  leaflet::addCircles(data = as_Spatial(dplyr::filter(Test, Ranking == "2 - 200")), group = "1 - 200", color = ~pal(Ranking), popup = paste("<b>Ranking:", dplyr::filter(Test, Ranking == "2 - 200")$Rank,"</b>", "<br>", 
                                                                                    "Habitat:", dplyr::filter(Test, Ranking == "2 - 200")$habtype, "<br>",
                                                                                    "Dataset:", dplyr::filter(Test, Ranking == "2 - 200")$Dataset, "<br>",
                           "Canopy height:", dplyr::filter(Test, Ranking == "2 - 200")$Canopy_Height, "<br>",
                           "Sand:", round(dplyr::filter(Test, Ranking == "2 - 200")$afsandno + dplyr::filter(Test, Ranking == "2 - 200")$agsandno), "<br>",
                           "Coord x:", dplyr::filter(Test, Ranking == "2 - 200")$coords.x1, "<br>",
                           "Coord y:", dplyr::filter(Test, Ranking == "2 - 200")$coords.x2, "<br>",
                           "Lon:", dplyr::filter(Test, Ranking == "2 - 200")$Lon, "<br>",
                           "Lat:", dplyr::filter(Test, Ranking == "2 - 200")$Lat))%>% 
    leaflet::addCircles(data = as_Spatial(dplyr::filter(Test, Ranking == "Richness Trend")), group = "Richness Trend", color = ~pal(Ranking), popup = paste("<b>Ranking:", dplyr::filter(Test, Ranking == "Richness Trend")$Rank,"</b>", "<br>", 
                                                                                    "Habitat:", dplyr::filter(Test, Ranking == "Richness Trend")$habtype, "<br>",
                                                                                    "Dataset:", dplyr::filter(Test, Ranking == "Richness Trend")$Dataset, "<br>",
                           "Canopy height:", dplyr::filter(Test, Ranking == "Richness Trend")$Canopy_Height, "<br>",
                           "Sand:", round(dplyr::filter(Test, Ranking == "Richness Trend")$afsandno + dplyr::filter(Test, Ranking == "Richness Trend")$agsandno), "<br>",
                           "Coord x:", dplyr::filter(Test, Ranking == "Richness Trend")$coords.x1, "<br>",
                           "Coord y:", dplyr::filter(Test, Ranking == "Richness Trend")$coords.x2, "<br>",
                           "Lon:", dplyr::filter(Test, Ranking == "Richness Trend")$Lon, "<br>",
                           "Lat:", dplyr::filter(Test, Ranking == "Richness Trend")$Lat))   
}

l <- l %>%
  addLayersControl(baseGroups = names(esri),
                   overlayGroups = c("Richness Trend", "1 - 200", "201 - 400", "401 - 600"),
                   options = layersControlOptions(collapsed = TRUE)) %>%
  addMeasure(position = "topleft",
             primaryLengthUnit = "meters",
             primaryAreaUnit = "hectares")

l %>% addLegend("bottomright", pal = pal ,title = "Rank",opacity = 1, values = Test$Ranking) %>%
  addEasyButton(easyButton(
    icon="fa-crosshairs", title="Locate Me",
    onClick=JS("function(btn, map){ map.locate({setView: true}); }")))
```