---
title: "Resilient Landscapes in ecology"
author: "Derek Corcoran"
date: "`r Sys.Date()`"
output:
  ioslides_presentation:
    widescreen: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      error = FALSE,
                      cache = TRUE)

library(ggplot2)
library(tidyterra)
library(leaflet.minicharts)
library(leaflet)
library(plotly)
library(htmlwidgets)
library(leafpop)
library(tidyverse)
library(gganimate)
library(ggrepel)
library(terra)
library(sf)
library(viridis)
```

## Resiliency

```{r, echo=FALSE}
simulate_abundance <- function(ecosystem, steady_state, stressor_start, stressor_duration, stressor_slope = -0.1, recovery_duration, recovery_slope = 0.1, top_recovery = 100, noise = 2) {
  time <- seq(1, (stressor_start + stressor_duration + recovery_duration))
  
  abundance <- c(rep(steady_state, stressor_start - 1),
                 steady_state * exp(stressor_slope * (1:stressor_duration)))
  
  Min <- min(abundance)
  
  Left <- length(time) - length(abundance)
  
  recovery <- c(Min * exp(recovery_slope * (1:Left)))
  
  recovery <- ifelse(recovery > top_recovery, top_recovery, recovery)
  
  abundance <- c(abundance, recovery)
  
  abundance <- abundance + rnorm(length(abundance), mean = 0, sd = noise)
  
  data.frame(time = time, ecosystem = rep(ecosystem, length(time)), abundance = abundance, stressor_duration = stressor_duration, stressor_slope = stressor_slope, recovery_slope = recovery_slope)
}

resistent <- simulate_abundance("resistent", steady_state = 100, stressor_start = 31, stressor_duration = 2, stressor_slope = -0.05, recovery_slope = 0.1,recovery_duration = 67)

resilient <- simulate_abundance("resilient", steady_state = 100, stressor_start = 31, stressor_duration = 10, recovery_duration = 59,  stressor_slope = -0.05, recovery_slope = 0.1)

non_resilient <- simulate_abundance("non-resilient", steady_state = 100, stressor_start = 31, stressor_duration = 10, recovery_duration = 59,  stressor_slope = -0.05, recovery_slope = 0.04,  top_recovery = 70)


all_data <- dplyr::bind_rows(resistent, resilient, non_resilient)

accumulate_by <- function(dat, var) {
  var <- lazyeval::f_eval(var, dat)
  lvls <- plotly:::getLevels(var)
  dats <- lapply(seq_along(lvls), function(x) {
    cbind(dat[var %in% lvls[seq(1, x)], ], frame = lvls[[x]])
  })
  dplyr::bind_rows(dats)
}


fig <- all_data
fig <- fig %>% accumulate_by(~time)

gg <- ggplot(fig, aes(x=time, y=abundance)) +
  geom_vline(xintercept = 30, lty = 2) +
  geom_path(aes(frame = frame, color = ecosystem)) + facet_grid(ecosystem~.) + theme_bw() + theme(legend.position = "none")
gg <- ggplotly(gg)

gg <- gg %>% animation_opts(
  frame = 100, 
  transition = 0, 
  redraw = FALSE
)
gg <- gg %>% animation_slider(
  hide = T
)
gg <- gg %>% animation_button(
  x = 1, xanchor = "right", y = 0, yanchor = "bottom"
)
gg
```

## Example of nature based solutions

```{r Mols}
Mols_SF <- read_csv("https://raw.githubusercontent.com/derek-corcoran-barrios/derek-corcoran-barrios.github.io/master/ResilientLandscapes/210201_Mols_PlantData%20.csv") %>%
  # Filter only size 10 in PlotSize
  dplyr::filter(PlotSize == 10.00, YEAR == 2017) %>% 
  dplyr::select("BlockNo",  "Latitude", "Longitude", 
"InitialHabitat") %>%
  distinct() %>% 
  st_as_sf(coords = c(3,2), crs = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs +towgs84=0,0,0") %>% 
  group_split(BlockNo) %>% 
  purrr::map(~sample_n(.x,size = 1)) %>% 
  reduce(bind_rows)
```

* rewildling (NBS) vs enclousure

```{r, cache = FALSE}
pal <- colorFactor(c('#66c2a5','#fc8d62','#8da0cb'), domain =c("Rangeland", "Forest", "Meadow"))


l <-leaflet(data = Mols_SF)  %>% 
  addCircleMarkers(popup = ~as.character(InitialHabitat), label = ~as.character(InitialHabitat), color = ~pal(InitialHabitat), opacity = 0.8) %>% addLegend("bottomright", pal = pal, values = ~InitialHabitat,
                                                                                                                                                            title = "Initial Habitat 2017",
                                                                                                                                                            opacity = 1) 

esri <- grep("^Esri", providers, value = TRUE)
esri <- esri[c(5,2,4,10)]

for (provider in esri) {
  l <- l %>% addProviderTiles(provider, group = provider)
}

l %>%
  addLayersControl(baseGroups = names(esri),
                   options = layersControlOptions(collapsed = TRUE)) %>%
  addMiniMap(tiles = esri[[4]], toggleDisplay = TRUE,
             position = "topleft")
```

## Rewildilng Mols Bjerge National Park (cont)

```{r PredRichness, include=FALSE}
NewData <- download.file("https://github.com/derek-corcoran-barrios/derek-corcoran-barrios.github.io/raw/master/ResilientLandscapes/NewDataPlot.rds", "NewDataPlot.rds")

NewData <- readRDS("NewDataPlot.rds")

file.remove("NewDataPlot.rds")
```


```{r PredRichness2}
G <-ggplot(NewData, aes(x = Year, y = Predicted)) +
  geom_path(aes(color = treatment)) +
  facet_wrap(~initial_habitat) +
  theme_bw() +
  labs(y = "Alpha Diversity")

plotly::ggplotly(G)
```

## On a landscape

```{r PopupMap}
Resilients <- list()
Plots <- list()
  
for(i in 1:30){
  Resilients[[i]] <- simulate_abundance("resilient", steady_state = 100, stressor_start = 31, stressor_duration = 10, recovery_duration = 59,  stressor_slope = -0.05, recovery_slope = 0.1)
  Plots[[i]] <- ggplot(Resilients[[i]], aes(x = time, y = abundance)) + geom_path() + theme_bw()
}

Resilients <- Resilients |> 
  purrr::reduce(dplyr::bind_rows)


Resilients_sum <- Resilients |> 
  summarise(abundance = sum(abundance), .by = time)


non_resilients <- list()

for(i in 1:5){
  non_resilients[[i]] <- simulate_abundance("non-resilient", steady_state = 100, stressor_start = 31, stressor_duration = 10, recovery_duration = 59,  stressor_slope = -0.05, recovery_slope = 0.04,  top_recovery = 70)
  Plots[[i + 30]] <- ggplot(non_resilients[[i]], aes(x = time, y = abundance)) + geom_path() + theme_bw()
}

non_resilients <- non_resilients |> 
  purrr::reduce(dplyr::bind_rows)


non_resilients_sum <- non_resilients |> 
  summarise(abundance = sum(abundance), .by = time)

Forest <- terra::rast("Forest.tif")


Forest_Int <- terra::rast("Forest_Int.tif")

Forest_Poly <- terra::ifel(Forest_Int == 1, 1, NA) |> 
  as.polygons() |> disagg()

Forest_Poly$area <- terra:::expanse(Forest_Poly, unit = "ha")

BigArea <- Forest_Poly[Forest_Poly$area == max(Forest_Poly$area),]


ContArea <- crop(Forest, BigArea)

set.seed(2024)
Sample <- spatSample(ContArea, 100, xy = TRUE, as.points = T) |> 
  tidyterra::slice_max(order_by = focal_mean, n = 35) |> 
  tidyterra::arrange(desc(focal_mean)) 

Sample$ID <- 1:nrow(Sample)

set.seed(2024)

Sample$Type <- sample(c("Resilient", "Non-resilient"), size = nrow(Sample), replace = T, prob = c(0.85, 0.15))

Sample <- Sample |> tidyterra::arrange(desc(Type))



Sample_sf <- terra::project(Sample, y = "epsg:4623")

Pal <- colorFactor(c("red", "blue"), domain = sort(Sample_sf$Type))


leaflet() |> addProviderTiles("Esri.WorldImagery") |> 
  addCircleMarkers(data = Sample_sf, radius = 3, color = ~Pal(Type), group = "pnt") |> 
  addPopupGraphs(Plots, group = "pnt", width = 200, height = 200)

```


## All together

```{r cumulative}
all <- dplyr::bind_rows(Resilients, non_resilients) |> 
  summarise(abundance = sum(abundance), .by = time)

ggplot(all, aes(x = time, y = abundance)) + geom_path()
```

## Higher connectivity leads to higher diversity

```{r diversityConnect}
lines <- terra::vect("Lines2500.shp") |> 
  terra::project(y = "epsg:4623")
Diversity <- read.csv("DiversityMap.csv") |> 
  dplyr::mutate(pi = 10*(pi/max(pi))) |> 
  terra::vect(geom = c("x", "y"), crs = "epsg:4326")

color_palette <- colorNumeric(
  palette = "YlGnBu",
  domain = Diversity$pi,
  reverse = T
)

leaflet() |>
    addProviderTiles("Esri.WorldImagery") |>
    addPolylines(data = lines, weight = 1, color = "red") |>
    addCircleMarkers(data = Diversity, radius = ~pi, fillOpacity = 0.8, color = ~color_palette(pi), popup = leafpop::popupTable(as.data.frame(Diversity))) |> addLegend(pal =  color_palette, values = Diversity$pi, title = "Genetic diversity", position  = "bottomleft")
```

## Area vs diversity

```{r areaDiv}
Diverse <- read_csv("Diversity.csv") |> 
  dplyr::mutate(pi = pi/max(pi))
G <- ggplot(Diverse, aes(x = Area, y = pi)) + geom_smooth(method = "lm") + geom_point() + theme_bw()+ labs(x = "Area [ha]", y = "Genetic diversity")
plotly::ggplotly(G) 
```

## Grassland connectivity

```{r}

```

