<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 2 Investigación reproducible | Manipulación de datos e investigación reproducible en R</title>
  <meta name="description" content="Este libro es una compañia al curso, análisis y manipulación de datos en R" />
  <meta name="generator" content="bookdown 0.19 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 2 Investigación reproducible | Manipulación de datos e investigación reproducible en R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="Cover.png" />
  <meta property="og:description" content="Este libro es una compañia al curso, análisis y manipulación de datos en R" />
  <meta name="github-repo" content="/derek-corcoran-barrios/derek-corcoran-barrios.github.io/tree/master/Libro" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 2 Investigación reproducible | Manipulación de datos e investigación reproducible en R" />
  
  <meta name="twitter:description" content="Este libro es una compañia al curso, análisis y manipulación de datos en R" />
  <meta name="twitter:image" content="Cover.png" />

<meta name="author" content="Derek Corcoran" />


<meta name="date" content="2020-08-17" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="tidydata.html"/>
<link rel="next" href="tidyverso.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Manipupación de datos en R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Requerimientos</a><ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#antes-de-comenzar"><i class="fa fa-check"></i><b>0.1</b> Antes de comenzar</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#descripción-del-curso"><i class="fa fa-check"></i><b>0.2</b> Descripción del curso</a></li>
<li class="chapter" data-level="0.3" data-path="index.html"><a href="index.html#objetivos-del-curso"><i class="fa fa-check"></i><b>0.3</b> Objetivos del curso</a></li>
<li class="chapter" data-level="0.4" data-path="index.html"><a href="index.html#contenidos"><i class="fa fa-check"></i><b>0.4</b> Contenidos</a></li>
<li class="chapter" data-level="0.5" data-path="index.html"><a href="index.html#metodología"><i class="fa fa-check"></i><b>0.5</b> Metodología</a></li>
<li class="chapter" data-level="0.6" data-path="index.html"><a href="index.html#evaluación"><i class="fa fa-check"></i><b>0.6</b> Evaluación</a></li>
<li class="chapter" data-level="0.7" data-path="index.html"><a href="index.html#libros-de-consulta"><i class="fa fa-check"></i><b>0.7</b> Libros de consulta</a></li>
<li class="chapter" data-level="0.8" data-path="index.html"><a href="index.html#bibliografía"><i class="fa fa-check"></i><b>0.8</b> Bibliografía</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="tidydata.html"><a href="tidydata.html"><i class="fa fa-check"></i><b>1</b> Tidy Data y manipulación de datos</a><ul>
<li class="chapter" data-level="1.1" data-path="tidydata.html"><a href="tidydata.html#paquetes-necesarios-para-este-capítulo"><i class="fa fa-check"></i><b>1.1</b> Paquetes necesarios para este capítulo</a></li>
<li class="chapter" data-level="1.2" data-path="tidydata.html"><a href="tidydata.html#tidy-data"><i class="fa fa-check"></i><b>1.2</b> Tidy data</a></li>
<li class="chapter" data-level="1.3" data-path="tidydata.html"><a href="tidydata.html#dplyr"><i class="fa fa-check"></i><b>1.3</b> dplyr</a><ul>
<li class="chapter" data-level="1.3.1" data-path="tidydata.html"><a href="tidydata.html#pipeline"><i class="fa fa-check"></i><b>1.3.1</b> Pipeline (%&gt;%)</a></li>
<li class="chapter" data-level="1.3.2" data-path="tidydata.html"><a href="tidydata.html#summarize"><i class="fa fa-check"></i><b>1.3.2</b> summarize</a></li>
<li class="chapter" data-level="1.3.3" data-path="tidydata.html"><a href="tidydata.html#group_by"><i class="fa fa-check"></i><b>1.3.3</b> group_by</a></li>
<li class="chapter" data-level="1.3.4" data-path="tidydata.html"><a href="tidydata.html#mutate"><i class="fa fa-check"></i><b>1.3.4</b> mutate</a></li>
<li class="chapter" data-level="1.3.5" data-path="tidydata.html"><a href="tidydata.html#filter"><i class="fa fa-check"></i><b>1.3.5</b> filter</a></li>
<li class="chapter" data-level="1.3.6" data-path="tidydata.html"><a href="tidydata.html#select"><i class="fa fa-check"></i><b>1.3.6</b> select</a></li>
<li class="chapter" data-level="1.3.7" data-path="tidydata.html"><a href="tidydata.html#joins"><i class="fa fa-check"></i><b>1.3.7</b> Joins</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="tidydata.html"><a href="tidydata.html#left-join"><i class="fa fa-check"></i><b>1.4</b> left join</a><ul>
<li class="chapter" data-level="1.4.1" data-path="tidydata.html"><a href="tidydata.html#ejercicios"><i class="fa fa-check"></i><b>1.4.1</b> Ejercicios</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="reproducible.html"><a href="reproducible.html"><i class="fa fa-check"></i><b>2</b> Investigación reproducible</a><ul>
<li class="chapter" data-level="2.1" data-path="reproducible.html"><a href="reproducible.html#paquetes-necesarios-para-este-capítulo-1"><i class="fa fa-check"></i><b>2.1</b> Paquetes necesarios para este capítulo</a></li>
<li class="chapter" data-level="2.2" data-path="reproducible.html"><a href="reproducible.html#investigación-reproducible"><i class="fa fa-check"></i><b>2.2</b> Investigación reproducible</a></li>
<li class="chapter" data-level="2.3" data-path="reproducible.html"><a href="reproducible.html#guardando-nuestro-proyecto-en-github"><i class="fa fa-check"></i><b>2.3</b> Guardando nuestro proyecto en github</a><ul>
<li class="chapter" data-level="2.3.1" data-path="reproducible.html"><a href="reproducible.html#que-es-github"><i class="fa fa-check"></i><b>2.3.1</b> Que es github?</a></li>
<li class="chapter" data-level="2.3.2" data-path="reproducible.html"><a href="reproducible.html#creando-un-proyecto-de-github-en-rstudio"><i class="fa fa-check"></i><b>2.3.2</b> creando un proyecto de github en RStudio</a></li>
<li class="chapter" data-level="2.3.3" data-path="reproducible.html"><a href="reproducible.html#los-tres-principales-pasos-de-un-repositorio"><i class="fa fa-check"></i><b>2.3.3</b> Los tres principales pasos de un repositorio</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="reproducible.html"><a href="reproducible.html#reproducibilidad-en-r"><i class="fa fa-check"></i><b>2.4</b> Reproducibilidad en R</a><ul>
<li class="chapter" data-level="2.4.1" data-path="reproducible.html"><a href="reproducible.html#creando-un-rmarkdown"><i class="fa fa-check"></i><b>2.4.1</b> Creando un Rmarkdown</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="reproducible.html"><a href="reproducible.html#subtitulo-1"><i class="fa fa-check"></i>subtitulo 1</a><ul>
<li class="chapter" data-level="" data-path="reproducible.html"><a href="reproducible.html#subtítulo-2"><i class="fa fa-check"></i>subtítulo 2</a></li>
<li class="chapter" data-level="2.4.2" data-path="reproducible.html"><a href="reproducible.html#ejercicios-1"><i class="fa fa-check"></i><b>2.4.2</b> Ejercicios</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="tidyverso.html"><a href="tidyverso.html"><i class="fa fa-check"></i><b>3</b> El Tidyverso y tidyr</a><ul>
<li class="chapter" data-level="3.1" data-path="tidyverso.html"><a href="tidyverso.html#paquetes-necesarios-para-este-capítulo-2"><i class="fa fa-check"></i><b>3.1</b> Paquetes necesarios para este capítulo</a></li>
<li class="chapter" data-level="3.2" data-path="tidyverso.html"><a href="tidyverso.html#el-tidyverso"><i class="fa fa-check"></i><b>3.2</b> El tidyverso</a><ul>
<li class="chapter" data-level="3.2.1" data-path="tidyverso.html"><a href="tidyverso.html#readr"><i class="fa fa-check"></i><b>3.2.1</b> readr</a></li>
<li class="chapter" data-level="3.2.2" data-path="tidyverso.html"><a href="tidyverso.html#dplyr-1"><i class="fa fa-check"></i><b>3.2.2</b> dplyr</a></li>
<li class="chapter" data-level="3.2.3" data-path="tidyverso.html"><a href="tidyverso.html#tidyr"><i class="fa fa-check"></i><b>3.2.3</b> tidyr</a></li>
<li class="chapter" data-level="3.2.4" data-path="tidyverso.html"><a href="tidyverso.html#ggplot2"><i class="fa fa-check"></i><b>3.2.4</b> ggplot2</a></li>
<li class="chapter" data-level="3.2.5" data-path="tidyverso.html"><a href="tidyverso.html#purrr"><i class="fa fa-check"></i><b>3.2.5</b> purrr</a></li>
<li class="chapter" data-level="3.2.6" data-path="tidyverso.html"><a href="tidyverso.html#forcats"><i class="fa fa-check"></i><b>3.2.6</b> forcats</a></li>
<li class="chapter" data-level="3.2.7" data-path="tidyverso.html"><a href="tidyverso.html#stringr"><i class="fa fa-check"></i><b>3.2.7</b> stringr</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="tidyverso.html"><a href="tidyverso.html#tidyr-1"><i class="fa fa-check"></i><b>3.3</b> tidyr</a><ul>
<li class="chapter" data-level="3.3.1" data-path="tidyverso.html"><a href="tidyverso.html#gather"><i class="fa fa-check"></i><b>3.3.1</b> gather</a></li>
<li class="chapter" data-level="3.3.2" data-path="tidyverso.html"><a href="tidyverso.html#spread"><i class="fa fa-check"></i><b>3.3.2</b> spread</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="tidyverso.html"><a href="tidyverso.html#ejercicios-2"><i class="fa fa-check"></i><b>3.4</b> Ejercicios</a><ul>
<li class="chapter" data-level="3.4.1" data-path="tidyverso.html"><a href="tidyverso.html#ejercicio-1-2"><i class="fa fa-check"></i><b>3.4.1</b> Ejercicio 1</a></li>
<li class="chapter" data-level="3.4.2" data-path="tidyverso.html"><a href="tidyverso.html#ejercicio-2-1"><i class="fa fa-check"></i><b>3.4.2</b> Ejercicio 2</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="visualizacion.html"><a href="visualizacion.html"><i class="fa fa-check"></i><b>4</b> Visualización de datos</a><ul>
<li class="chapter" data-level="4.1" data-path="visualizacion.html"><a href="visualizacion.html#paquetes-necesarios-para-este-capítulo-3"><i class="fa fa-check"></i><b>4.1</b> Paquetes necesarios para este capítulo</a></li>
<li class="chapter" data-level="4.2" data-path="visualizacion.html"><a href="visualizacion.html#el-esqueleto"><i class="fa fa-check"></i><b>4.2</b> El esqueleto</a></li>
<li class="chapter" data-level="4.3" data-path="visualizacion.html"><a href="visualizacion.html#por-que-usamos-aes-y"><i class="fa fa-check"></i><b>4.3</b> Por que usamos aes() y +</a></li>
<li class="chapter" data-level="4.4" data-path="visualizacion.html"><a href="visualizacion.html#geom_algo"><i class="fa fa-check"></i><b>4.4</b> geom_algo</a><ul>
<li class="chapter" data-level="4.4.1" data-path="visualizacion.html"><a href="visualizacion.html#una-variable-categórica-una-continua"><i class="fa fa-check"></i><b>4.4.1</b> Una variable categórica una continua</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="visualizacion.html"><a href="visualizacion.html#combinando-geoms"><i class="fa fa-check"></i><b>4.5</b> Combinando geoms</a><ul>
<li class="chapter" data-level="4.5.1" data-path="visualizacion.html"><a href="visualizacion.html#el-orden-importa"><i class="fa fa-check"></i><b>4.5.1</b> El orden importa</a></li>
<li class="chapter" data-level="4.5.2" data-path="visualizacion.html"><a href="visualizacion.html#dos-variables-continuas"><i class="fa fa-check"></i><b>4.5.2</b> Dos variables continuas</a></li>
<li class="chapter" data-level="4.5.3" data-path="visualizacion.html"><a href="visualizacion.html#combinando-varios-gráficos-con-facet_wrap"><i class="fa fa-check"></i><b>4.5.3</b> Combinando varios gráficos con facet_wrap</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="modelos.html"><a href="modelos.html"><i class="fa fa-check"></i><b>5</b> Modelos en R</a><ul>
<li class="chapter" data-level="5.1" data-path="modelos.html"><a href="modelos.html#paquetes-necesarios-para-este-capítulo-4"><i class="fa fa-check"></i><b>5.1</b> Paquetes necesarios para este capítulo</a></li>
<li class="chapter" data-level="5.2" data-path="modelos.html"><a href="modelos.html#modelos-estadísticos"><i class="fa fa-check"></i><b>5.2</b> Modelos estadísticos</a><ul>
<li class="chapter" data-level="5.2.1" data-path="modelos.html"><a href="modelos.html#ejemplo"><i class="fa fa-check"></i><b>5.2.1</b> Ejemplo</a></li>
<li class="chapter" data-level="5.2.2" data-path="modelos.html"><a href="modelos.html#representando-un-modelo-en-r"><i class="fa fa-check"></i><b>5.2.2</b> Representando un modelo en R</a></li>
<li class="chapter" data-level="5.2.3" data-path="modelos.html"><a href="modelos.html#volvamos-al-ejemplo-de-las-plantas"><i class="fa fa-check"></i><b>5.2.3</b> Volvamos al ejemplo de las plantas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="loops.html"><a href="loops.html"><i class="fa fa-check"></i><b>6</b> Loops (purrr) y bibliografía (rticles)</a><ul>
<li class="chapter" data-level="6.1" data-path="loops.html"><a href="loops.html#paquetes-necesarios-para-este-capítulo-5"><i class="fa fa-check"></i><b>6.1</b> Paquetes necesarios para este capítulo</a></li>
<li class="chapter" data-level="6.2" data-path="loops.html"><a href="loops.html#generando-una-receta"><i class="fa fa-check"></i><b>6.2</b> Generando una receta</a><ul>
<li class="chapter" data-level="6.2.1" data-path="loops.html"><a href="loops.html#dioxido-de-nitrógeno-en-madrid"><i class="fa fa-check"></i><b>6.2.1</b> Dioxido de nitrógeno en Madrid</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="loops.html"><a href="loops.html#empezando-el-loop"><i class="fa fa-check"></i><b>6.3</b> Empezando el loop</a><ul>
<li class="chapter" data-level="6.3.1" data-path="loops.html"><a href="loops.html#volvamos-a-nuestra-receta"><i class="fa fa-check"></i><b>6.3.1</b> Volvamos a nuestra receta</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="presentacion.html"><a href="presentacion.html"><i class="fa fa-check"></i><b>7</b> Presentaciones en R</a><ul>
<li class="chapter" data-level="7.1" data-path="presentacion.html"><a href="presentacion.html#paquetes-necesarios-para-este-capítulo-6"><i class="fa fa-check"></i><b>7.1</b> Paquetes necesarios para este capítulo</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="soluciones.html"><a href="soluciones.html"><i class="fa fa-check"></i><b>8</b> Soluciones a problemas</a><ul>
<li class="chapter" data-level="8.1" data-path="soluciones.html"><a href="soluciones.html#capítulo-1"><i class="fa fa-check"></i><b>8.1</b> Capítulo 1</a><ul>
<li class="chapter" data-level="8.1.1" data-path="soluciones.html"><a href="soluciones.html#ejercicio-1-3"><i class="fa fa-check"></i><b>8.1.1</b> Ejercicio 1</a></li>
<li class="chapter" data-level="8.1.2" data-path="soluciones.html"><a href="soluciones.html#ejercicio-2-2"><i class="fa fa-check"></i><b>8.1.2</b> Ejercicio 2</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="soluciones.html"><a href="soluciones.html#capítulo-2"><i class="fa fa-check"></i><b>8.2</b> Capítulo 2</a><ul>
<li class="chapter" data-level="8.2.1" data-path="soluciones.html"><a href="soluciones.html#ejercicio-1-4"><i class="fa fa-check"></i><b>8.2.1</b> Ejercicio 1</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="soluciones.html"><a href="soluciones.html#capítulo-3"><i class="fa fa-check"></i><b>8.3</b> Capítulo 3</a><ul>
<li class="chapter" data-level="8.3.1" data-path="soluciones.html"><a href="soluciones.html#ejercicio-1-5"><i class="fa fa-check"></i><b>8.3.1</b> Ejercicio 1</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="referencias.html"><a href="referencias.html"><i class="fa fa-check"></i><b>9</b> Referencias</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Publicado con bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Manipulación de datos e investigación reproducible en R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="reproducible" class="section level1">
<h1><span class="header-section-number">Capítulo 2</span> Investigación reproducible</h1>
<div id="paquetes-necesarios-para-este-capítulo-1" class="section level2">
<h2><span class="header-section-number">2.1</span> Paquetes necesarios para este capítulo</h2>
<p>Para este capítulo se necesita tener instalado los paquetes <em>rmarkdown</em>, <em>knitr</em> y <em>stargazer</em></p>
<p>En este capítulo se explicará qué es investigación reproducible, cómo aplicarla usando github más los paquetes <em>rmarkdown</em> <span class="citation">(Allaire et al. <a href="#ref-Allaire2018">2018</a>)</span> y <em>knitr</em> <span class="citation">(Xie <a href="#ref-xie2015">2015</a>)</span>. Además, se aprenderá a usar tablas usando <em>knitr</em> <span class="citation">(Xie <a href="#ref-xie2015">2015</a>)</span> y <em>stargazer</em> <span class="citation">(Hlavac <a href="#ref-hlavak2018">2018</a>)</span></p>
<p>Recuerda que este libro es un apoyo para el curso BIO4022, puedes seguir la clase de este curso en este <a href="https://derek-corcoran-barrios.github.io/Clase2/Clase2InvestigacionReproducible">link</a>, y en cuanto el video de la clase encontrarás un link <a href="https://youtu.be/CGvQPlpBcso">acá</a>.</p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/CGvQPlpBcso" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
</iframe>
</div>
<div id="investigación-reproducible" class="section level2">
<h2><span class="header-section-number">2.2</span> Investigación reproducible</h2>
<p>La investigación reproducible no es lo mismo que la investigación replicable. La replicabilidad implica que experimentos o estudios llevados a cabo en condiciones similares nos llevarán a conclusiones similares. La investigación reproducible implica que desde los mismos datos y/o el mismo código se generarán los mismos resultados.</p>
<div class="figure" style="text-align: center"><span id="fig:reproducible"></span>
<img src="Reproducible.png" alt="Continuo de reproducibilidad (extraido de Peng 2011)" width="80%" />
<p class="caption">
Figura 2.1: Continuo de reproducibilidad (extraido de Peng 2011)
</p>
</div>
<p>En la figura <a href="reproducible.html#fig:reproducible">2.1</a> vemos el continuo de reproducibilidad <span class="citation">(Peng <a href="#ref-peng2011reproducible">2011</a>)</span>. En este continuo tenemos el ejemplo de no reproducibilidad como una publicación sin código. Se pasa de menos a más reproducible por la publicación y el código que generó los resultados y gráficos; seguido por la publicación, el código y los datos que generan los resultados y gráficos; y por último código, datos y texto entrelazados de forma tal que al correr el código obtenemos exactamente la mismma publicación que leímos.</p>
<p>Esto tiene muchas ventajas, incluyendo el que es más fácil aplicar exactamente los mismos métodos a otra base de datos. Basta poner la nueva base de datos en el formato que tenía el autor de la primera publicación y podremos comparar los resultados.</p>
<p>Además en un momento en que la ciencia está basada cada vez más en bases de datos, se puede poner en el código la recolección y/o muestreo de datos.</p>
</div>
<div id="guardando-nuestro-proyecto-en-github" class="section level2">
<h2><span class="header-section-number">2.3</span> Guardando nuestro proyecto en github</h2>
<div id="que-es-github" class="section level3">
<h3><span class="header-section-number">2.3.1</span> Que es github?</h3>
<p>Github es una suerte de dropbox o google drive pensado para la investigación reproducible, en donde cada proyecto es un <em>repositorio</em>. La mayoría de los investigadores que trabajan en investigación reproducible dejan todo su trabajo documentado en sus repositorios, lo cual permite interactuar con otros autores.</p>
</div>
<div id="creando-un-proyecto-de-github-en-rstudio" class="section level3">
<h3><span class="header-section-number">2.3.2</span> creando un proyecto de github en RStudio</h3>
<p>Para crear un proyecto en github presionamos <strong>start a project</strong> en la página inicial de nuestra cuenta, como vemos en la figura <a href="reproducible.html#fig:Start">2.2</a></p>
<div class="figure" style="text-align: center"><span id="fig:Start"></span>
<img src="StartAProject.png" alt="Para empezar un projecto en github, debes presionar Start a project en tu página de inicio" width="80%" />
<p class="caption">
Figura 2.2: Para empezar un projecto en github, debes presionar Start a project en tu página de inicio
</p>
</div>
<p>Luego se debe crear un nombre único, y sin cambiar nada más presiona <strong>create repository</strong> en el botón verde como vemos en la figura <a href="reproducible.html#fig:Name">2.3</a>.</p>
<div class="figure" style="text-align: center"><span id="fig:Name"></span>
<img src="NombreRepo.png" alt="Crea el nombre de tu repositorio y apreta el boton create repository" width="80%" />
<p class="caption">
Figura 2.3: Crea el nombre de tu repositorio y apreta el boton create repository
</p>
</div>
<p>Esto te llevará a una página donde aparecerá una url de tu nuevo repositorio como en la figura <a href="reproducible.html#fig:ssh">2.4</a></p>
<div class="figure" style="text-align: center"><span id="fig:ssh"></span>
<img src="GitAdress.png" alt="El contenido del cuadro en el cual dice ssh es la url de tu repisitorio" width="80%" />
<p class="caption">
Figura 2.4: El contenido del cuadro en el cual dice ssh es la url de tu repisitorio
</p>
</div>
<p>Para incorporar tu proyecto en tu repositorio, lo primero que debes hacer es generar un proyecto en RStudio. Para esto debes ir en el menú superior de <em>Rstudio</em> a <em>File &gt; New Project &gt; Git</em> como se ve en las figuras <a href="reproducible.html#fig:NewProject">2.5</a> y <a href="reproducible.html#fig:NewProject">2.5</a>.</p>
<div class="figure" style="text-align: center"><span id="fig:NewProject"></span>
<img src="NewProject.png" alt="Menú para crear un proyecto nuevo" width="80%" />
<p class="caption">
Figura 2.5: Menú para crear un proyecto nuevo
</p>
</div>
<div class="figure" style="text-align: center"><span id="fig:Git"></span>
<img src="Git.png" alt="Seleccionar git dentro de las opciones" width="80%" />
<p class="caption">
Figura 2.6: Seleccionar git dentro de las opciones
</p>
</div>
<p>Luego seleccionar la ubicación del proyecto nuevo y pegar el url que aparece en la figura <a href="reproducible.html#fig:ssh">2.4</a> en el espacio que dice <strong>Repository URL:</strong>, como muestra en la figura <a href="reproducible.html#fig:GitRstudio">2.7</a>.</p>
<div class="figure" style="text-align: center"><span id="fig:GitRstudio"></span>
<img src="GitRstudio.png" alt="Pegar el url del repositorio en el cuadro de dialogo Repository URL:" width="80%" />
<p class="caption">
Figura 2.7: Pegar el url del repositorio en el cuadro de dialogo Repository URL:
</p>
</div>
<p>Cuando tu proyecto de R ya este siguiendo los cambios en github, te aparecerá una pestaña git dentro de la ventana superior derecha de tu sesión de RStudio, tal como vemos en la figura <a href="reproducible.html#fig:GitPan">2.8</a></p>
<div class="figure" style="text-align: center"><span id="fig:GitPan"></span>
<img src="GitPan.png" alt="Al incluir tu repositorio en tu sesión de Rstudio, aparecera la pestaña git en la ventana superior derecha" width="80%" />
<p class="caption">
Figura 2.8: Al incluir tu repositorio en tu sesión de Rstudio, aparecera la pestaña git en la ventana superior derecha
</p>
</div>
</div>
<div id="los-tres-principales-pasos-de-un-repositorio" class="section level3">
<h3><span class="header-section-number">2.3.3</span> Los tres principales pasos de un repositorio</h3>
<p>Github es todo un mundo, existen muchas funciones y hay expertos en el uso de github. En este curso, nos enfocaremos en los 3 pasos principales de un repositorio: <em>add</em>, <em>commit</em> y <em>push</em>. Para entender bien qué significa cada uno de estos pasos, tenemos que entender que existen dos repositorios en todo momento: uno local (en tu computador) y otro remoto (en github.com). Los dos primeros pasos <em>add</em> y <em>commit</em>, solo generan cambios en tu repositorio local. Mientras que <em>push</em>, salva los cambios al repositorio remoto.</p>
<div id="git-add" class="section level4">
<h4><span class="header-section-number">2.3.3.1</span> git add</h4>
<p>Esta función es la que agrega archivos a tu repositorio local. Solo estos archivos serán guardados en github. Github tienen un límite de tamaño de repositorio de 1 GB y de archivos de 100 MB, ya que si bien te dan repositorios ilimitados, el espacio de cada uno no lo es, en particular en cuanto a bases de datos. Para adicionar un archivo a tu repositorio tan solo debes selecionar los archivos en la pestaña git. Al hacer eso una letra A verde aparecerá en vez de los dos signos de interrogación amarillos, como vemos en la figura <a href="reproducible.html#fig:Add">2.9</a>. En este caso solo adicionamos al repositorio el archivo <em>Analisis.r</em> pero no el resto.</p>
<div class="figure" style="text-align: center"><span id="fig:Add"></span>
<img src="GitAdd.png" alt="Al incluir tu repositorio en tu sesión de Rstudio, aparecera la pestaña git en la ventana superior derecha" width="80%" />
<p class="caption">
Figura 2.9: Al incluir tu repositorio en tu sesión de Rstudio, aparecera la pestaña git en la ventana superior derecha
</p>
</div>
</div>
<div id="git-commit" class="section level4">
<h4><span class="header-section-number">2.3.3.2</span> git commit</h4>
<p>Cuando ocupas el comando <em>commit</em> estas guardando los cambios de los archivos que adicionaste en tu repositorio local. Para hacer esto en Rstudio, en la misma pestaña de git, debes presionar el botón <em>commit</em> como vemos en la figura <a href="reproducible.html#fig:Commit">2.10</a>.</p>
<div class="figure" style="text-align: center"><span id="fig:Commit"></span>
<img src="Commit.png" alt="Para guardar los cambios en tu repositorio apretar commit en la pestaña git de la ventana superior derecha" width="80%" />
<p class="caption">
Figura 2.10: Para guardar los cambios en tu repositorio apretar commit en la pestaña git de la ventana superior derecha
</p>
</div>
<p>Al presionar <em>commit</em>, se abrirá una ventana emergente, donde deberás escribir un mensaje que describa lo que guardarás. Una vez echo eso, presiona <em>commit</em> nuevamente en la ventana emergente como aparece en la figura <a href="reproducible.html#fig:MensajeCommit">2.11</a>.</p>
<div class="figure" style="text-align: center"><span id="fig:MensajeCommit"></span>
<img src="MensajeCommit.png" alt="Escribir un mensaje que recuerde los cambios que hiciste en la ventana emergente" width="80%" />
<p class="caption">
Figura 2.11: Escribir un mensaje que recuerde los cambios que hiciste en la ventana emergente
</p>
</div>
</div>
<div id="git-push" class="section level4">
<h4><span class="header-section-number">2.3.3.3</span> git push</h4>
<p>Finalmente, <em>push</em> te permitirá guardar los cambios en tu repositorio remoto, lo cual asegura tus datos en la nube y además lo hace disponible a otros investigadores. Luego de apretar <em>commit</em> en la ventana emergente (figura <a href="reproducible.html#fig:MensajeCommit">2.11</a>), podemos presionar <em>push</em> en la flecha verde de la ventana emergente como se ve el a figura <a href="reproducible.html#fig:push">2.12</a>. Luego se nos pedirá nuestro nombre de usuario y contraseña, y ya podemos revisar que nuestro repositorio esta online entrando a nuestra sesión de github.</p>
<div class="figure" style="text-align: center"><span id="fig:push"></span>
<img src="Push.png" alt="Para guardar en el repositorio remoto apretar push en la ventana emergente" width="80%" />
<p class="caption">
Figura 2.12: Para guardar en el repositorio remoto apretar push en la ventana emergente
</p>
</div>
</div>
</div>
</div>
<div id="reproducibilidad-en-r" class="section level2">
<h2><span class="header-section-number">2.4</span> Reproducibilidad en R</h2>
<p>Existen varios paquetes que permiten que hagamos investigación reproducible en <code>R</code>, pero sin duda los más relevantes son <em>rmarkdown</em> y <em>knitr</em>. Ambos paquetes funcionan en conjunto cuando generamos un archivo <em>Rmd</em> (Rmarkdown), en el cual ocupamos al mismo tiempo texto, código de R y otros elementos para generar un documento word, pdf, página web, presentación y/o aplicación web (fig <a href="reproducible.html#fig:Rmark">2.13</a>).</p>
<div class="figure" style="text-align: center"><span id="fig:Rmark"></span>
<img src="Rmark.png" alt="El objetivo de Rmarkdown es el unir código de r con texto y datos para generar un documento reproducible" width="80%" />
<p class="caption">
Figura 2.13: El objetivo de Rmarkdown es el unir código de r con texto y datos para generar un documento reproducible
</p>
</div>
<div id="creando-un-rmarkdown" class="section level3">
<h3><span class="header-section-number">2.4.1</span> Creando un Rmarkdown</h3>
<p>Para crear un archivo Rmarkdown, simplemente ve a el menu <em>File &gt; New file &gt; Rmarkdown</em> y con eso habrás creado un nuevo archivo <em>Rmd</em>. Veremos algunos de los elementos más típicos de un archivo Rmarkdown.</p>
<div id="markdown" class="section level4">
<h4><span class="header-section-number">2.4.1.1</span> Markdown</h4>
<p>El markdown es la parte del archivo en que simplemente escribimos texto, aunque tiene algunos detalles para el formato como generar texto en negrita, cursiva, títulos y subtitulos.</p>
<p>Para hacer que un texto este en <strong>negrita</strong>, se debe poner entre dos asteriscos <code>**negrita**</code>, para que un texto aparezca en <em>cursiva</em> debe estar entre asteriscos <code>*cursiva*</code>. Otros ejemplos son los títulos de distintos niveles, los cuales se denotan con distintos números de <code>#</code>, así los siguientes 4 títulos o subtítulos:</p>
</div>
</div>
</div>
<div id="subtitulo-1" class="section level2 unnumbered">
<h2>subtitulo 1</h2>
<div id="subtítulo-2" class="section level3 unnumbered">
<h3>subtítulo 2</h3>
<div id="subtítulo-3" class="section level4 unnumbered">
<h4>subtítulo 3</h4>
<div id="subtítulo-4" class="section level5 unnumbered">
<h5>subtítulo 4</h5>
<p>se vería de la siguiente manera en el código</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb23-1" data-line-number="1"><span class="co">## subtitulo 1</span></a>
<a class="sourceLine" id="cb23-2" data-line-number="2"></a>
<a class="sourceLine" id="cb23-3" data-line-number="3"><span class="co">### subtítulo 2</span></a>
<a class="sourceLine" id="cb23-4" data-line-number="4"></a>
<a class="sourceLine" id="cb23-5" data-line-number="5"><span class="co">#### subtítulo 3</span></a>
<a class="sourceLine" id="cb23-6" data-line-number="6"></a>
<a class="sourceLine" id="cb23-7" data-line-number="7"><span class="co">##### subtítulo 4</span></a></code></pre></div>
</div>
</div>
<div id="chunks" class="section level4">
<h4><span class="header-section-number">2.4.1.2</span> Chunks</h4>
<p>Los <em>chunks</em> son una de las partes más importantes del un Rmarkdown. En estos es donde se agrega el código de R (u otros lenguajes de programación). Lo cual permíte que el producto de nuestro código no sea sólo un escrito con resultados pegados, sino que efectivamente generados en el mismo documento que nuestro escrito. La forma más fácil de agregar un chunk es apretando el botón de <em>insert chunk</em> en Rstudio, este boton se encuentra en la ventana superior izquierda de nuestra sesión de RStudio, tal como se muestra en la figura <a href="reproducible.html#fig:Insertchunk">2.14</a></p>
<div class="figure" style="text-align: center"><span id="fig:Insertchunk"></span>
<img src="Insertchunk.png" alt="Al apretar el botón insert chunk, aparecera un espacio en el cuál insertar código" width="80%" />
<p class="caption">
Figura 2.14: Al apretar el botón insert chunk, aparecera un espacio en el cuál insertar código
</p>
</div>
<p>Al apretar este botón aparecera un espacio, ahí se puede agregar un código como el que aparece a continuación, y ver a continuación los resultados.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode markdown"><code class="sourceCode markdown"><a class="sourceLine" id="cb24-1" data-line-number="1"><span class="bn">```{r}</span></a>
<a class="sourceLine" id="cb24-2" data-line-number="2"><span class="bn">library(tidyverse)</span></a>
<a class="sourceLine" id="cb24-3" data-line-number="3"><span class="bn">iris %&gt;% group_by(Species) %&gt;% summarize(Petal.Length = mean(Petal.length))</span></a>
<a class="sourceLine" id="cb24-4" data-line-number="4"><span class="bn">```</span></a></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre><code>## # A tibble: 3 x 2
##   Species    Petal.Length
##   &lt;fct&gt;             &lt;dbl&gt;
## 1 setosa             1.46
## 2 versicolor         4.26
## 3 virginica          5.55</code></pre>
<div id="opciones-de-los-chunks" class="section level5">
<h5><span class="header-section-number">2.4.1.2.1</span> Opciones de los chunks</h5>
<p>Existen muchas opciones para los chunks, una documentación completa podemos encontrarle en el siguiente <a href="https://yihui.name/knitr/options/">link</a>, pero acá mostraremos los más comunes:</p>
<ul>
<li><em>echo</em> = T o F muestro o no el código, respectivamente</li>
<li><em>message</em> = T o F muestra mensajes de paquetes, respectivamente</li>
<li><em>warning</em> = T o F muestra advertencias, respectivamente</li>
<li><em>eval</em> = T o F evaluar o no el código, respectivamente</li>
<li><em>cache</em> = T o F guarda o no el resultado, respectivamente</li>
</ul>
</div>
</div>
<div id="inline-code" class="section level4">
<h4><span class="header-section-number">2.4.1.3</span> inline code</h4>
<p>Los <em>inline codes</em> son útiles para agregar algún valor en el texto, como por ejemplo el valor de p o la media. Para usarlo, se debe poner un backtick (comilla simple hacia atrás), r, el código en cuestion y otro backtick como se ve a continuación <code>`r R_código`</code>. No podemos poner cualquier cosa en un <em>inline code</em>, ya que sólo puede generar vectores, lo cuál muchas veces requiere de mucha creatividad para lograr lo que queremos. Por ejemplo si se quisiera poner el promedio del largo del sépalo de la base da dato <code>iris</code> en un <em>inline code</em> pondríamos <code>`r mean(iris$Sepal.Length)`</code>, lo cual resultaría en 5.8433333. Como en un texto se vería extraño un número con 7 cifras significativas, querríamos usar ademas la función <code>round</code>, para que tenga 2 cifras significativas, para eso ponemos el siguiente inline code <code>`r round(mean(iris$Sepal.Length),2)`</code> que da como resultado 5.84. Esto se puede complejizar más aún si se quiere trabajar con una tabla resumen. Por ejemplo, si quisieramos listar el promedio del tamaño de sépalo usaríamos <code>summarize</code> de <em>dplyr</em>, pero esto nos daría como resultado un data.frame, el cual no aparece si intentamos hacer un inline code. Partamos por ver como se vería el código donde obtuvieramos la media del tamaño del sépalo.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb27-1" data-line-number="1">iris <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(Species) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarize</span>(<span class="dt">Mean =</span> <span class="kw">mean</span>(Sepal.Length))</a></code></pre></div>
<p>El resultado de ese código lo veríamos <a href="reproducible.html#tab:SummarySepaltab">2.1</a></p>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<table>
<caption>
<span id="tab:SummarySepaltab">Tabla 2.1: </span>Resumen del promedio del largo de sépalo de las flores del genero Iris.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Species
</th>
<th style="text-align:right;">
Mean
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
setosa
</td>
<td style="text-align:right;">
5.006
</td>
</tr>
<tr>
<td style="text-align:left;">
versicolor
</td>
<td style="text-align:right;">
5.936
</td>
</tr>
<tr>
<td style="text-align:left;">
virginica
</td>
<td style="text-align:right;">
6.588
</td>
</tr>
</tbody>
</table>
<p>Para sacar de este data frame el vector de la media podríamos subsetearlo con el signo <code>$</code>. Entonces si queremos sacar como vector la columna <em>Mean</em> del data frame que creamos, haríamos lo siguiente <code>`r (iris %&gt;% group_by(Species) %&gt;% summarize(Mean = mean(Sepal.Length)))$Mean`</code>. Esto daría como resultado 5.006, 5.936, 6.588.</p>
</div>
</div>
<div id="ejercicios-1" class="section level3">
<h3><span class="header-section-number">2.4.2</span> Ejercicios</h3>
<div id="ejercicio-1-1" class="section level4">
<h4><span class="header-section-number">2.4.2.1</span> Ejercicio 1</h4>
<p>Usando la base de datos <em>iris</em>, crea un inline code que diga cuál es la media del largo del pétalo de la especie <em>Iris virginica</em></p>
<p>La solución a este ejercicio se encuentra en el capítulo <a href="soluciones.html#soluciones">8</a></p>
</div>
<div id="tablas-en-rmarkdown" class="section level4">
<h4><span class="header-section-number">2.4.2.2</span> Tablas en Rmarkdown</h4>
<p>La función más típica para generar tablas en un archivo <em>rmd</em> es <code>kable</code> del paquete <em>knitr</em>, que en su forma más simple se incluye un dataframe como único argumento. Además de esto, podemos agregar algunos parámetros como <em>caption</em>, que nos permite poner un título a la tabla o <em>row.names</em>, que si se pone como se ve en el código (FALSE) no mostrará en la tabla los nombres de las filas, tal como se ve en la tabla <a href="reproducible.html#tab:SummaryMeans">2.2</a>.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb29-1" data-line-number="1">DF &lt;-<span class="st"> </span>iris <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(Species) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarize_all</span>(mean)</a>
<a class="sourceLine" id="cb29-2" data-line-number="2"><span class="kw">kable</span>(DF, <span class="dt">caption =</span> <span class="st">&quot;Promedio por especie de todas las variables de la base de datos iris.&quot;</span>, </a>
<a class="sourceLine" id="cb29-3" data-line-number="3">    <span class="dt">row.names =</span> <span class="ot">FALSE</span>)</a></code></pre></div>
<table>
<caption>
<span id="tab:SummaryMeans">Tabla 2.2: </span>Promedio por especie de todas las variables de la base de datos iris.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Species
</th>
<th style="text-align:right;">
Sepal.Length
</th>
<th style="text-align:right;">
Sepal.Width
</th>
<th style="text-align:right;">
Petal.Length
</th>
<th style="text-align:right;">
Petal.Width
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
setosa
</td>
<td style="text-align:right;">
5.006
</td>
<td style="text-align:right;">
3.428
</td>
<td style="text-align:right;">
1.462
</td>
<td style="text-align:right;">
0.246
</td>
</tr>
<tr>
<td style="text-align:left;">
versicolor
</td>
<td style="text-align:right;">
5.936
</td>
<td style="text-align:right;">
2.770
</td>
<td style="text-align:right;">
4.260
</td>
<td style="text-align:right;">
1.326
</td>
</tr>
<tr>
<td style="text-align:left;">
virginica
</td>
<td style="text-align:right;">
6.588
</td>
<td style="text-align:right;">
2.974
</td>
<td style="text-align:right;">
5.552
</td>
<td style="text-align:right;">
2.026
</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<h3> Referencias</h3>
<div id="refs" class="references">
<div id="ref-Allaire2018">
<p>Allaire, JJ, Yihui Xie, Jonathan McPherson, Javier Luraschi, Kevin Ushey, Aron Atkins, Hadley Wickham, Joe Cheng, and Winston Chang. 2018. <em>Rmarkdown: Dynamic Documents for R</em>. <a href="https://CRAN.R-project.org/package=rmarkdown">https://CRAN.R-project.org/package=rmarkdown</a>.</p>
</div>
<div id="ref-hlavak2018">
<p>Hlavac, Marek. 2018. <em>Stargazer: Well-Formatted Regression and Summary Statistics Tables</em>. Bratislava, Slovakia: Central European Labour Studies Institute (CELSI). <a href="https://CRAN.R-project.org/package=stargazer">https://CRAN.R-project.org/package=stargazer</a>.</p>
</div>
<div id="ref-peng2011reproducible">
<p>Peng, Roger D. 2011. “Reproducible Research in Computational Science.” <em>Science</em> 334 (6060). American Association for the Advancement of Science: 1226–7.</p>
</div>
<div id="ref-xie2015">
<p>Xie, Yihui. 2015. <em>Dynamic Documents with R and Knitr</em>. 2nd ed. Boca Raton, Florida: Chapman; Hall/CRC. <a href="http://yihui.name/knitr/">http://yihui.name/knitr/</a>.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="tidydata.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="tidyverso.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Libro.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
