---
title: "Map Trojborg"
author: "Derek Corcoran"
date: "8/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, cache = FALSE)
library(tidyverse)
library(leaflet)
library(sf)
library(raster)

Trojborg_Raster <- read_rds("TrojborgRaster.rds")

Trojborg_Raster <- Trojborg_Raster[[1]] %>% projectRaster(crs ="+proj=longlat +datum=WGS84 +no_defs")

Trojborg_Roads <- read_rds("roads_Trojborg.rds") %>% st_transform(crs ="+proj=longlat +datum=WGS84 +no_defs")

Trojborg <- read_sf("GroupsTrojborg.shp") %>% 
  st_transform(crs = "+proj=longlat +datum=WGS84 +no_defs") %>% 
  mutate(Group = case_when(Group == 1 ~ "A1",
                           Group == 2 ~ "A2",
                           Group == 3 ~ "B1",
                           Group == 4 ~ "B2",
                           Group == 5 ~ "C1",
                           Group == 6 ~ "C2"))

Trojborg_Centroids <- read_sf("Trojborg_centroids.shp") %>% 
  st_transform(crs = "+proj=longlat +datum=WGS84 +no_defs")%>% 
  mutate(Group = case_when(Group == 1 ~ "A1",
                           Group == 2 ~ "A2",
                           Group == 3 ~ "B1",
                           Group == 4 ~ "B2",
                           Group == 5 ~ "C1",
                           Group == 6 ~ "C2"))

Trojborg_Centroids <- Trojborg_Centroids %>% 
  mutate(Code = paste(Group, formatC(rowid, digits = 2, flag = "0"), sep = "_"), Treatment = NA) %>% group_by(Code) %>% group_split()

Treatments <- LETTERS[1:3]

for(i in 1:length(Trojborg_Centroids)){
  set.seed(i)
  Trojborg_Centroids[[i]]$Treatment <- sample(Treatments, replace = F)
}

Trojborg_Centroids <- Trojborg_Centroids %>% reduce(bind_rows) %>% 
  mutate(Code = paste(Code, Treatment, sep = "_")) %>% 
  dplyr::select(-Treatment)

write_sf(Trojborg_Centroids, "Final_Centroids_Trojborg.shp")


Trojborg_Monitor <- list()

for(i in 1:nrow(Trojborg)){
  set.seed(i)
  Mask <- mask(Trojborg_Raster, Trojborg[i,])
  try({
  Pres <- Trojborg_Centroids %>% dplyr::filter(Group == Trojborg[i,]$Group[1]) %>% as_Spatial()
  
    RandomPoints <- dismo::randomPoints(Mask, n = 30, p = Pres) %>% 
    as.data.frame() %>% 
    st_as_sf(coords = c(1,2), crs ="+proj=longlat +datum=WGS84 +no_defs") %>% 
    mutate(Group = Trojborg[i,]$Group[1]) %>% 
    st_transform(crs = "+proj=utm +zone=32 +ellps=GRS80 +units=m +no_defs") %>% 
    st_buffer(dist = 25) %>% 
    st_transform(crs ="+proj=longlat +datum=WGS84 +no_defs") 
  for(j in i:nrow(RandomPoints)){
    if(j == 1){
      Temp <- RandomPoints[j,]
    }
    else if (j != 1 & sum(st_intersects(Temp, RandomPoints[j,], sparse = F)) == 0){
      Temp <- rbind(Temp, RandomPoints[j,])
      print(j)
    }
  }
  Trojborg_Monitor[[i]] <- Temp %>% st_centroid() %>% dplyr::distinct()
  })
}

cond <- !sapply(Trojborg_Monitor, is.null)

Trojborg_Monitor <- Trojborg_Monitor[cond]

Trojborg_Monitor <- Trojborg_Monitor %>% reduce(rbind) %>% dplyr::distinct()

Trojborg_Monitor <- Trojborg_Monitor %>% group_split(Group) %>% purrr::map(~tibble::rowid_to_column(.x)) %>% reduce(rbind)

separated_coord <- Trojborg_Monitor %>% 
  mutate(lat = unlist(map(Trojborg_Monitor$geometry,1)),
         long = unlist(map(Trojborg_Monitor$geometry,2))) %>% 
  as.data.frame() %>% 
  dplyr::select(lat, long) %>% 
  dplyr::distinct()

Trojborg_Monitor <- Trojborg_Monitor %>% 
  cbind(separated_coord) %>% 
  mutate(Code = paste("B", Group, rowid, sep = "_")) %>% 
  dplyr::select(-rowid)
write_sf(Trojborg_Monitor, "Trojborg_Monitor.shp")
```

```{r}
l <-leaflet()

esri <- grep("^Esri", providers, value = TRUE)
esri <- esri[c(5,2,4,10)]

pal <- colorFactor(
  palette = c("#9e0142", "#d53e4f", "#fee08b", "#ffffbf", "#66c2a5", "#3288bd"),
  domain= as.character(sort(unique(Trojborg_Centroids$Group))),
  ordered = TRUE,
  na.color = "#808080"
)

for (provider in esri) {
  l <- l %>% addProviderTiles(provider, group = provider)    
}

l <- l %>% 
    leaflet::addCircleMarkers(data = as_Spatial(Trojborg_Monitor), radius = 6, group = "Monitoring", color = ~"white", popup = paste("Lon:", Trojborg_Monitor$long, "<br>",
                           "Lat:", Trojborg_Monitor$lat, "<br>",
                           "Code:",Trojborg_Monitor$Code)) %>% 
    leaflet::addCircleMarkers(data = as_Spatial(Trojborg_Centroids), radius = 6, group = "Points", color = ~pal(Group), popup = paste("Lon:", Trojborg_Centroids$long, "<br>",
                           "Lat:", Trojborg_Centroids$lat, "<br>",
                           "Group:", Trojborg_Centroids$Group, "<br>", 
                           "Code:", Trojborg_Centroids$Code)) %>%
  addPolygons(data = as_Spatial(Trojborg), group = "Groups", color = ~pal(Group), fillColor = ~pal(Group), opacity = 0.8, popup = Trojborg$Group, fillOpacity = 0.8) %>% 
  addPolylines(data = Trojborg_Roads, color = "red", group = "Roads") %>% 
  addLayersControl(baseGroups = names(esri),
                   overlayGroups = c("Points", "Groups", "Monitoring", "Roads"),
                   options = layersControlOptions(collapsed = TRUE)) %>%
  addMeasure(position = "topleft",
             primaryLengthUnit = "meters",
             primaryAreaUnit = "hectares") %>% 
  hideGroup("Groups")

l %>% addLegend("bottomright", pal = pal ,title = "Trojborg sites",opacity = 1, values = Trojborg_Centroids$Group) %>%
  addEasyButton(easyButton(
    icon="fa-crosshairs", title="Locate Me",
    onClick=JS("function(btn, map){ map.locate({setView: true}); }")))

```
