---
title: "Mapas Interactivos con Leaflet"
author: "Derek Corcoran"
date: "`r format(Sys.time(), '%d/%m, %Y')`"
output:
  ioslides_presentation:
    widescreen: true
    incremental: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, cache = FALSE, tidy = TRUE, tidy.opts= list(blank = FALSE, width.cutoff = 60))
library(leaflet)
library(sf)
library(tidyverse)
library(rgdal)
library(raster)
library(rasterVis)
library(rworldxtra)
library(tidyverse)
library(gridExtra)
library(kableExtra)
options("kableExtra.html.bsTable" = T)
```

## Mapas interactivos

```{r, echo = FALSE}
download.file("https://raw.githubusercontent.com/derek-corcoran-barrios/derek-corcoran-barrios.github.io/master/Presentaciones_Espacial/Chile.zip", destfile = "Chile.zip")

unzip("Chile.zip")

Chile <- read_sf("Chile.shp")

Nothofagus <- read_csv("https://raw.githubusercontent.com/derek-corcoran-barrios/derek-corcoran-barrios.github.io/master/Presentaciones_Espacial/Nothofagus.csv")


Number_spp <- Nothofagus$scrubbed_species_binomial %>% unique() %>% length()

Spp_Names <- Nothofagus$scrubbed_species_binomial %>% unique()

## Desde https://colorbrewer2.org

Colores <- c("#a6cee3","#1f78b4","#b2df8a","#33a02c","#fb9a99","#e31a1c","#fdbf6f","#ff7f00","#cab2d6")

pal <- colorFactor(Colores, domain = Spp_Names)


leaflet() %>%  addTiles() %>% addCircleMarkers(data = Nothofagus, lat = ~latitude, lng = ~longitude,popup = ~scrubbed_species_binomial,
                                               color = ~pal(scrubbed_species_binomial),
                                               stroke = FALSE, fillOpacity = 0.5, group = "Especies") %>% 
  addLegend(data = Nothofagus, "bottomleft", pal = pal, values = ~scrubbed_species_binomial,
            title = "Especies",
            opacity = 1,
            group = "Leyenda"
  ) %>% addLayersControl(overlayGroups = c("Especies", "Leyenda"),
                         options = layersControlOptions(collapsed = FALSE))
```

## Cargamos paquetes

```{r, echo = FALSE, eval=TRUE}
library(leaflet)
library(rworldxtra)
library(raster)
library(sf)
library(tidyverse)
```
